### ISSUE TITLE
(bitvise-ssh-server) Wrong Checksum

### ISSUE THREAD

**Issue by jtcmedia** [mkevenaar/chocolatey-packages#103]
## Expected Behavior
package gets upgraded

## Current Behavior
package doesn't get upgraded, error in checksum

## Possible Solution
Manually run your update script and release a fixed package version. Bitvise must've changed the d/l w/o changing version number.

**Comment by mkevenaar** [comment]
@jtcmedia thanks for submitting this issue, a new build is triggered. A new version should be available soon on the CCR
