### ISSUE TITLE
Zettlr with TeX install

### ISSUE THREAD

**Issue by BrandonKMLee** [mkevenaar/chocolatey-packages#114]
## Current Behavior
https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/zettlr
Then install with chocolatey
- https://community.chocolatey.org/packages/miktex
- https://community.chocolatey.org/packages/texlive

## Possible Solution
The parameter that installs TeX by default.

**Comment by mkevenaar** [comment]
@BrandonKMLee a Chocolatey package cannot start an installation of more than 1 piece of software. Also if there are 2 packages that provide the same kind of application, I cannot add them as a dependency.

**Comment by BrandonKMLee** [comment]
@mkevenaar wait, then how can chocolatey install AHK as a dependency for other software?

**Comment by mkevenaar** [comment]
@BrandonKMLee You can have multiple dependencies, but they are 'and' dependencies, not 'or'. Based on your description, one of these packages could be used.

**Comment by BrandonKMLee** [comment]
Fair, but they do have a note saying that TeX is required for certain features https://docs.zettlr.com/en/installing-latex/
If not, I don't mind this turning into an optional flag.

**Comment by mkevenaar** [comment]
@BrandonKMLee The only way to process optional parameters are by using PowerShell. I cannot provide option A or B in a package and I am not allowed to call `choco install` or any other `choco` command within a Chocolatey package. I can't see how I can continue with this request.

**Comment by BrandonKMLee** [comment]
Apologies then, will ask help from them instead.
