### ISSUE TITLE
Current baseDir & dataDir parameters do not allow for spaces in the path

### ISSUE THREAD

**Issue by tristanwilson111** [mkevenaar/chocolatey-packages#115]
The way we process the inbound parameters here: 

https://github.com/mkevenaar/chocolatey-packages/blob/233fd0483b91fe98ae6750f2b38065ffd5fa7833/automatic/mysql/tools/chocolateyInstall.ps1#L63-L64

We are not able to pass paths with spaces, in my case "C:/Program Files/MySQL..."

The variable passed in is seen as "C:/Program Files"

I would troubleshoot this on my own, but unsure as to how to load the file locally to resolve this issue.

**Comment by mkevenaar** [comment]
No response after a month, closing issue
