### ISSUE TITLE
UltraVNC file associations, start menu links and icons not installed

### ISSUE THREAD

**Issue by nwmcsween** [mkevenaar/chocolatey-packages#116]
## Expected Behavior

* Desktop icons for all users get installed
* Start menu shortcuts get installed for all users
* Associate ultravnc with .vnc extensions

## Current Behavior

None of the above

## Possible Solution

* ???
* Profit?

## Steps to Reproduce (for bugs)

* Install

## Context

* Need to reinstall ultravnc manually in order to get proper associations, shortcuts, icons, etc.

## Your Environment

* Any?

**Comment by Neustradamus** [comment]
Dear all, @mkevenaar,

I have done a ticket to have a fix about bad UltraVNC version numbers in Chocolatey:
- https://github.com/mkevenaar/chocolatey-packages/issues/276

In more, I have done a ticket one year ago about 1.4.3.6:
- https://github.com/mkevenaar/chocolatey-packages/issues/222
