### ISSUE TITLE
(ExifTool) Website down, use SourceForge & not generate unnecessary text files

### ISSUE THREAD

**Issue by lucknaumann** [mkevenaar/chocolatey-packages#119]
## Expected Behavior

For this package to update, and not generate useless text files.

## Current Behavior

This package isn't updating because the old website is down. Packages can be found on SourceForge: https://sourceforge.net/projects/exiftool/.

This package also leaves a trail of old text files: "exiftool-{version}.zip.txt," which take up unnecessary space. These files are completely unnecessary as they only contain this: "C:\ProgramData\chocolatey\lib\exiftool\tools\exiftool(-k).exe."

## Possible Solution

Change the download path to download the latest version from SourceForge, and stop this package from generating unnecessary text files, or at least delete the old ones.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Thanks for maintaining this package. FYI regarding the site change, and request for the removal of unnecessary text file generation or removal of old text files.

## Your Environment

* Package Version used:
* Operating System and version:
* Chocolatey version:
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
The exiftool website is backup. This is no longer an issue
