### ISSUE TITLE
PowerToys install no longer silent, new installer has new commandline arguments

### ISSUE THREAD

**Issue by koolhand** [mkevenaar/chocolatey-packages#121]
## Expected Behavior
PowerToys installer should be silent.

## Current Behavior
With the update to PowerToys v0.53.1, installation is no longer silent - there is a licence prompt. This is the result of a changed installer platform for PowerToys.

## Possible Solution

* OLD: --silent --skip_dotnet_install
* NEW: -silent

See the [PowerToys docs](https://docs.microsoft.com/en-us/windows/powertoys/install#installer-args).

Note: It's built using a new installer platform (WiX), so the valid exit codes may have changed too.

## Steps to Reproduce (for bugs)

1. ```choco install powertoys```

## Context

In the v0.53.1 [PowerToys readme](https://github.com/microsoft/PowerToys/releases/tag/v0.53.1), the developers say that they have changed the installer platform to WiX, which would explain the commandline change.

The [relevant GitHub commit to the official Microsoft docs](https://github.com/MicrosoftDocs/windows-uwp/commit/0dd26869bc1d9d332ef26eb7ebfab6c8e8eb116a#diff-f474033c8673eeb07e5813d5ffe276b202af79650ce1adfd0f0c9b9d91734aaf) also shows the change to the commandline.

## Your Environment

* Package Version used: v0.53.1
* Operating System and version: Windows 11
* Chocolatey version: v0.11.3
* Install/uninstall gist: n/a

**Comment by mkevenaar** [comment]
Changes to fix this have been merged and will be available on the next release of PowerToys
