### ISSUE TITLE
musicbee Install failed

### ISSUE THREAD

**Issue by zhengda-skinny** [mkevenaar/chocolatey-packages#127]
musicbee Install failed

## Current Behavior

Chocolatey v1.1.0
Installing the following packages:
musicbee
By installing, you accept licenses for the packages.
Progress: Downloading musicbee 3.4.7805... 100%

musicbee v3.4.7805 [Approved]
musicbee package files install completed. Performing other installation steps.
The package musicbee wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Downloading musicbee
  from 'https://www.mediafire.com/file/a2bnughg9i2sv4u/MusicBeeSetup_3_4_Update1.zip'
WARNING: C:\Users\goalo\AppData\Local\Temp\chocolatey\musicbee\3.4.7805\file is of content type text/html; charset=UTF-8

Download of file (-1 B) completed.
Error - hashes do not match. Actual value was 'B9680467838BC7F053AC2B737965427B94B9B78F271603E181F9D9C339A973E9'.
ERROR: Checksum for 'C:\Users\goalo\AppData\Local\Temp\chocolatey\musicbee\3.4.7805\file' did not meet '405010d8a387e20aa5754b14732f37008a7733e646aa9c4290cf8dcb53e4003f' for checksum type 'sha
256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessar
y.
The install of musicbee was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - musicbee (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.
## Steps to Reproduce (for bugs)

1. choco install musicbee

## Your Environment

* Package Version used: musicbee 3.4.7805
* Operating System and version: Win10
* Chocolatey version: 1.1.0
* Install/uninstall gist: https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/musicbee

**Comment by mkevenaar** [comment]
Unfortunately Musicbee has changed their distribution method to use Mega upload, one that cannot be automated for download. I am looking for an alternative

**Comment by zhengda-skinny** [comment]
Hi Maurice

Please check the attatched image.



Maurice Kevenaar ***@***.***> 于 2022年4月28日周四 下午11:33写道：
