### ISSUE TITLE
Winrar 6.11 has wrong (possibly old) checksums

### ISSUE THREAD

**Issue by pitsi** [mkevenaar/chocolatey-packages#128]
## Expected Behavior
Chocolatey should install winrar without complaining about the checksum mismatch that is mentioned below.

## Current Behavior
As seen below, chocolatey fails to install winrar because the exe file fails to pass the checksum verification. When the mentioned `--ignore-checksums` parameter is used, chocolatey installs winrar with no issues.
```
Downloading winrar 64 bit
  from 'https://www.rarlab.com/rar/winrar-x64-611el.exe'
Progress: 100% - Completed download of C:\Users\user\AppData\Local\Temp\chocolatey\winrar\6.11\winrar-x64-611el.exe (3.38 MB).
Download of winrar-x64-611el.exe (3.38 MB) completed.
Error - hashes do not match. Actual value was '31DAA9F63B084D70EA66A578BBD590ED646EB39ED17E899F0808DDD19B741988'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\chocolatey\winrar\6.11\winrar-x64-611el.exe' did not meet '2b66d5eefe3c9ec9139f74f569ea8f863dfc2f81381baa1a6fda1e755ae39810' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
  winrar may be able to be automatically uninstalled.
The install of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
```

## Possible Solution
Update the checksums used by the winrar chocolatey package

## Steps to Reproduce (for bugs)
1. Just run `choco install winrar`.

## Context
Something must have changed in winrar's setup files, although their version remained the same.
I had downloaded and stored the forementioned installation file locally when v6.11 was released 2 months ago and its checksum was indeed the one that comes with the chocolatey package.

## Your Environment

* Package Version used: 6.11
* Operating System and version: Windows 10 19044.1682
* Chocolatey version: 1.1.0
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
@pitsi a new build has been triggered, once pushed and approved, this will solve this issue
