### ISSUE TITLE
Upgrading Powertoys from version 0.58 to 0.59 incorrectly try to install ARM on x64

### ISSUE THREAD

**Issue by jeansagi** [mkevenaar/chocolatey-packages#130]
Upgrading Powertoys from version 0.58 to 0.59 incorrectly try to install ARM on x64

## Expected Behavior

Now that there is an ARM and an x64 version, the chocolatey installer should choose the correct installer depending on the user platform.

n/a

## Current Behavior

ARM version of the Powertoys installer (PowerToysSetup-0.59.0-arm64.exe) is trying to get installed after issuing a "cup -y powertoys".

## Possible Solution

Add a rule to the installer to properly find the platform Chocolatey is being run on and choose the appropriate installer to execute it.

n/a

## Steps to Reproduce (for bugs)
In an x64 Windows (11 in my case), having version 0.58 of powertoys installed in a privileged powershell/cmd console run:
cup -y powertoys 

cup -y powertoys 

Produces this output:

Chocolatey v1.1.0
Upgrading the following packages:
powertoys
By upgrading, you accept licenses for the packages.

You have powertoys v0.58.0 installed. Version 0.59.0 is available based on your source(s).
Progress: Downloading powertoys 0.59.0... 100%

powertoys v0.59.0 [Approved]
powertoys package files upgrade completed. Performing other installation steps.
Installing powertoys...
WARNING: Installation of this MSI is not supported on this platform. Contact package maintainer(s) if you feel this is in error or if you need an architecture that is not available with the current packaging.
ERROR: Running ["C:\ProgramData\chocolatey\lib\powertoys\tools\PowerToysSetup-0.59.0-arm64.exe" -silent ] was not successful. Exit code was '1633'. Exit code indicates the following: Installation of this MSI is not supported on this platform. Contact package maintainer(s) if you feel this is in error or if you need an architecture that is not available with the current packaging..
The upgrade of powertoys was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\powertoys\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - powertoys (exited 1633) - Error while running 'C:\ProgramData\chocolatey\lib\powertoys\tools\chocolateyinstall.ps1'.
 See log for details.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

## Context

Version 0.59 cannot get installed. I'm trying to upgrade powertoys to version 0.59 using chocolatey.

## Your Environment

* Package Version used: Powertoys 0.58
* Operating System and version: Windows 11 Pro 21H2 (22000.708/1000.22000.708.0)
* Chocolatey version: 1.1.0
* Install/uninstall gist: n/a

**Comment by mkevenaar** [comment]
Thank you for submitting the issue, I will take a look at it

**Comment by mkevenaar** [comment]
This is fixed, a new version should be pushed soon and available for usage in a couple of hours.

**Comment by jeansagi** [comment]
Confirmed!

Thanks a lot.
