### ISSUE TITLE
(powertoys) dependencies need updated

### ISSUE THREAD

**Issue by TheNavyBear** [mkevenaar/chocolatey-packages#131]
PowerToys has been updated to need dotnet6 now instead of dontnetcore3. Please change the dependency from 'dotnetcore-desktopruntime' to 'dotnet-desktopruntime'.

## Context
Per the v0.58 release notes: "All uses of .NET Core 3.1 were removed. PowerToys now runs on .NET 6."

**Comment by mkevenaar** [comment]
This is fixed, a new version should be pushed soon and available for usage in a couple of hours.
