### ISSUE TITLE
(intel-mas) Intel MAS upgrade to 2.0 from 1.12 fails with 1603

### ISSUE THREAD

**Issue by jpluimers** [mkevenaar/chocolatey-packages#137]
## Expected Behavior

Upgrade from 1.12 to 2.0 succeeds without any errors

## Current Behavior

Fails with error 1603.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. reboot
2. from a UAC cmd prompt run `choco upgrade intel-mas --exit-when-reboot-detected --yes`

## Context

Trying to update Intel MAS from 1.12 to 2.0.

Linked [gist](https://gist.github.com/jpluimers/22405da7fb1c59c07a3863c514a5ff4e) has:

1. [chocolatey.log](https://gist.github.com/jpluimers/22405da7fb1c59c07a3863c514a5ff4e#file-chocolatey-log) - Chocolatey log (of command `choco upgrade intel-mas --exit-when-reboot-detected --yes`)
2. [IntelMAS_2.0.330_20220704122213.log](https://gist.github.com/jpluimers/22405da7fb1c59c07a3863c514a5ff4e#file-intelmas_2-0-330_20220704122213-log) - Intel MAS log
3. [installed.txt](https://gist.github.com/jpluimers/22405da7fb1c59c07a3863c514a5ff4e#file-installed-txt) - list of installed packages (output of command `choco list --localonly`) in case of other packages causing the problem

The discuss at the bottom of <https://community.chocolatey.org/packages/intel-mas> mentions that the choco-bot also runs into the same issue as per gist https://gist.github.com/choco-bot/0971bbfb9bd62c37549c79da84869824 (that is linked from the [intel-mas page](https://community.chocolatey.org/packages/intel-mas) under "Verification Testing Exemption: Dependency requires reboot.") which seems untrue: I run into this after a reboot.

## Your Environment

* Package Version used: 2.0
* Operating System and version: Windows v 10.0.19044.0
* Chocolatey version: Chocolatey v0.11.3
* Install/uninstall gist: https://gist.github.com/jpluimers/22405da7fb1c59c07a3863c514a5ff4e

**Comment by mkevenaar** [comment]
Seems like INTEL has changed some stuff, MAS 2.x only works with Intel's Optane-branded products

**Comment by jpluimers** [comment]
> Seems like INTEL has changed some stuff, MAS 2.x only works with Intel's Optane-branded products

Which leaves the question: what to do on systems that have the MAS 1.x version installed?

Is it possible to waren these users that an upgrade will fail? Is there an alternative?

(I use MAS 1.x to monitor health status of my Intel 520 SSD model SSDSC2CW180A3)

**Comment by mkevenaar** [comment]
You can pin it?
