### ISSUE TITLE
Cut release for 6.8.23 version of elasticsearch

### ISSUE THREAD

**Issue by TraGicCode** [mkevenaar/chocolatey-packages#141]
Would it be possible to cut a release for the latest 6.x version of the elasticsearch chocolatey package?  This version contained a log4j vulnerability fix that is critical in nature.

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.23.html

**Comment by mkevenaar** [comment]
https://community.chocolatey.org/packages/elasticsearch/6.8.23

This version is now pushed
