### ISSUE TITLE
(texstudio.install) Qt5 version of TexStudio 4.3.1 crashes on boot, should install Qt6 version instead

### ISSUE THREAD

**Issue by MijnheerD** [mkevenaar/chocolatey-packages#146]
## Expected Behavior

The package should be updated to install the Qt6 version of TexStudio, i.e. `https://github.com/texstudio-org/texstudio/releases/download/4.3.1/texstudio-4.3.1-win-qt6.exe` .

## Current Behavior

Chocolatey installs the Qt5 version of TexStudio by default. 

## Possible Solution

Change the `au_GetLatest` function in the `update.ps1` script to search for the Qt6 executable. Possibly it would be enough to change line 11 in the script to ` $re  = "download/.+/texstudio-(.+)-win-qt6.exe" `, but I am no expert so this might not work.

## Context

The Qt5 version of TexStudio 4.3.1 has a documented bug on Windows, crashing the program on startup (see also this issue: https://github.com/texstudio-org/texstudio/issues/2569). The solution is to install the Qt6 version instead, as Qt5 is deprecated.

## Your Environment

* Package Version used: 4.3.1
* Operating System and version: Windows 10, 21H2
* Chocolatey version: 1.1.0

**Comment by mkevenaar** [comment]
This should be fixed now, a new package will be build and will be available in the next couple of hours
