### ISSUE TITLE
[microsoft-windows-terminal] installed for user, not machine

### ISSUE THREAD

**Issue by teknowledgist** [mkevenaar/chocolatey-packages#152]
## Expected Behavior
When an administrator installs the package, unprivileged users can run the application.

## Current Behavior
An admin account (successfully) installs the package and can run it, but my daily driver account (unprivileged as is best practice) gets a 

    Windows cannot access the specified device, path, or file.  you may not have the appropriate permissions to access the item.

despite being able to view it.  (Permissions are `read`, but not `read & execute`.)  The error is the same trying to right-click and `run as administrator`, which means I have to start it from a script or elevated cmd or PoSh window.  

Since Chocolatey requires admin rights, this package can't be installed by my user account.

## Possible Solution
Not sure.  Is this a package problem or a Microsoft problem (which wouldn't surprise me)?  

## Steps to Reproduce (for bugs)
1.  As an admin:  `choco install microsoft-windows-terminal -y`
2.  As any other user attempt to run `wt.exe`

## Your Environment
* Package Version used:  1.15.2874.0
* Operating System and version:  Win10 21H2
* Chocolatey version:  1.2.0

**Comment by mkevenaar** [comment]
This should be fixed here: https://github.com/mkevenaar/chocolatey-packages/commit/d0fe41cc2490f8ce8e10c154ad46b379088ac230
