### ISSUE TITLE
(samsung-magician) Loud install in German

### ISSUE THREAD

**Issue by Destroy666x** [mkevenaar/chocolatey-packages#156]
## Expected Behavior
Samsung Magician should be silently/auto installed and with English language.

## Current Behavior
You have to use the installer manually and the language is German.

## Possible Solution
I think the AHK script doesn't simply work? No idea.

## Steps to Reproduce (for bugs)
1. Just install the package, I did from GUI.

## Context
-

## Your Environment
* Package Version used: 7.2.0.930
* Operating System and version: Windows 10.0.1945
* Chocolatey version: 1.2.1

**Comment by mkevenaar** [comment]
This should be fixed now
