### ISSUE TITLE
(wireshark) install fails on AppVeyor since 3.0

### ISSUE THREAD

**Issue by gpotter2** [mkevenaar/chocolatey-packages#16]
## Current Behavior
We’re seeing general failures on our AppVeyor tests that used to perform `choco install wireshark` successfully. This only happens since 3.0 and seems to be related to the new dependency « vcredist140 »

Here are the logs of one of the failing tests (please ignore the top error, unrelated): https://ci.appveyor.com/api/buildjobs/collw9fshr6cmlo8/log

## Context
An automated test build of Scapy: https://github.com/secdev/scapy/blob/master/.appveyor.yml#L36

## Your Environment

* Package Version used: 3.0.0
* Operating System and version: https://www.appveyor.com/updates/
* Chocolatey version: v0.10.11
* Install/uninstall gist: latest

## What you’ve tried
I tried to manually install the failing packages:
https://ci.appveyor.com/api/buildjobs/jk8kj2svv9k9yaei/log
As advised on Chocolatey’s gitter, to no avail.

Any help will be greatly appreciated, thanks for your work !

**Comment by mkevenaar** [comment]
Hi, thanks for contacting me, 

I needed to add the vcredist140 as a dependancy to get the installation working. As @AdmiringWorm already suggested on gitter, try to installde KB dependencies without executing them

`choco install -n KB3033929 KB2919355 kb2999226`

If there are any more failing packages, add them to the list.

Hope this helps,

Maurice

**Comment by mkevenaar** [comment]
I noticed that one package id is invalid, could you try to build with this list?

**Comment by gpotter2** [comment]
It seems that this did the trick 😄 thanks
https://ci.appveyor.com/api/buildjobs/s3lnh52tmis60g15/log
I’ll just make sure everything works as expected and close this issue.

**Comment by gpotter2** [comment]
Thanks again for your support,
Good day

**Comment by mkevenaar** [comment]
@gpotter2 if I am allowed to make an suggestion and if you have time, could you try and figure out wich KB package is causing this and create an issue on that repo? Perhaps we can improve that package to get it working without this workaround...

**Comment by gpotter2** [comment]
Not sure exactly how to do that. So far:
- Only using the above on `KB3033929`: https://ci.appveyor.com/project/secdev/scapy/builds/23480566/job/765o0i8m7dw9trye (failed)
- Only using the above on `KB2919355`: https://ci.appveyor.com/project/secdev/scapy/builds/23480582/job/vb1mhtq3602u6law (failed)
- Only using the above on `kb2999226`: https://ci.appveyor.com/project/secdev/scapy/builds/23480606/job/npda18l58r1nvrnc (failed)

**Comment by mkevenaar** [comment]
@gpotter2 I think all tree packages do not work on the AppVeyor environment. I would like to suggest to go to the package page and open an issue there. 

Hope that helps!

**Comment by AdmiringWorm** [comment]
I've done some digging around, and believe I've found the reason those packages don't work on appveyor.

A required service is disabled on appveyor (the windows update service), and because it's disabled no updates can be installed (nor can the packages detect if they are already installed).

All three packages depend on an extension to make the installation of updates simpler, the author of that extension closed a issue for the inability to install updates on appveyor explaining it is by design, as he do not wish to force the running of the required service.

**Comment by gpotter2** [comment]
Thanks for your explanation.

Apparently, there is a trick to restart this service: https://github.com/cocur/slugify/pull/193. I guess I’ll use it in our tests :-) Don’t know if it could be included at some point, or if It should be reported to AppVeyor
