### ISSUE TITLE
exiftool: build versions >12.47 are broken.

### ISSUE THREAD

**Issue by jedfrechette** [mkevenaar/chocolatey-packages#161]
As reported by multiple users on the community package page [1], all versions of the exiftool package newer than 12.47 fail to run. With the latest version (12.54) running `exiftool -h` reports the following error

```
Can't locate PAR.pm in @INC (you may need to install the PAR module) (@INC contains: .) at -e line 629.
````

Downgrading to version 12.47 seems to be the only workaround for this issue currently.

[1] https://community.chocolatey.org/packages/exiftool

**Comment by mkevenaar** [comment]
From a quick look, that seems to be an issue with the software and not with the package. I'll have a look at it soon

**Comment by mkevenaar** [comment]
It seems that a code change caused this. I am pusing a new version of the latest version and should be available shortly
