### ISSUE TITLE
google drive choco pagkage error

### ISSUE THREAD

**Issue by psjamesp** [mkevenaar/chocolatey-packages#165]
Error message when trying to upgrade google drive to 68.0.2.0

## Current Behavior

Error Message 
## Steps to Reproduce (for bugs)

1. choco upgrade googledrive
2.
3.
4.

## Context

ERROR: Running ["C:\Users\JamesPetty\AppData\Local\Temp\chocolatey\googledrive\68.0.2.0\GoogleDriveSetup.exe" --silent --desktop_shortcut ] was not successful. Exit code was '1638'. Exit code indicates the following: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'googledrive' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The upgrade of googledrive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\googledrive\tools\chocolateyInstall.ps1'.
 See log for details.

## Your Environment

* Package Version used: 68.0.2.0
* Operating System and version: Windows 11
* Chocolatey version: 1.2.1
* Install/uninstall gist:

**Comment by junefish** [comment]
Same happening to me.  I tried uninstalling and reinstalling and got the following output: https://pastebin.com/b88JbRUb
