### ISSUE TITLE
MongoDB 6.1.1 failing due to feature removed from downloaded msi

### ISSUE THREAD

**Issue by TheFlo** [mkevenaar/chocolatey-packages#166]
## Context

MongoDB package installation is failing due to an error during mongodb.install installation:
This seems to be caused by a feature specified in the installation script which have been removed from the downloaded msi.

## Current Behavior

![image](https://user-images.githubusercontent.com/4168994/214846964-a1420292-1a0d-4e6d-a49a-103aca171df6.png)

## Steps to Reproduce (for bugs)

run ```choco install mongodb --install-arguments="'/l*v c:\mongodb_msi_install.log'"```

in the logs we can find:

```
DEBUG: Error 2711:  The specified Feature name ('Client') not found in Feature Table.
MSI (s) (F4:0C) [14:06:11:148]: Product: MongoDB 6.1.1 2008R2Plus SSL (64 bit) -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: Client, , 

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: Client, , 
Action ended 14:06:11: CostFinalize. Return value 3.
Action ended 14:06:11: INSTALL. Return value 3.
```

## Possible Solution
Removing ```Client``` from ```ADDLOCAL``` in ```$silentArgs``` at line 6 of ```mongodb.install\tools\chocolateyInstall.ps1``` should fix the issue.

![image](https://user-images.githubusercontent.com/4168994/214847597-29189799-45d8-4c89-b1a2-d290dce80765.png)

**There might be more feature to remove in the future as the list doesn't match what we can choose during manual installation.**

## Your Environment
* Package Version used: 6.1.1
* Operating System and version: Windows 10 Pro - 21H2 - 19044.2486
* Chocolatey version: Chocolatey v1.2.1

**Comment by sebastienPinel** [comment]
Same thing is happening on version 6.2.1, I guess nothing have been done on this
