### ISSUE TITLE
Windows Terminal is stuck in version 1.15. Version

### ISSUE THREAD

**Issue by jeansagi** [mkevenaar/chocolatey-packages#169]
Windows Terminal is stuck in version 1.15. and version 1.16 stable is out for almos **two weeks**.

## Expected Behavior
Windows Terminal stable version is supposed to be available for upgrade.

## Current Behavior
Windows Terminal does not get upgraded.

## Possible Solution
Review update scripts for something to fix.

## Steps to Reproduce (for bugs)
1. choco upgrade -y all (Does not upgrade to version 1.16)
2. choco upgrade -y microsoft-windows-terminal (Says: *microsoft-windows-terminal v1.15.3465.0 is the latest version available based on your source(s).*)
3. choco outdated does not reporte a ner version of windows-terminal

## Context
It is supposed that if a stable new version of Windows-Termminal is out, chocolatey should offer it for upgrade moreover that 2 weeks have passed.

## Your Environment
* Package Version used: **microsoft-windows-terminal 1.15.3465.0**
* Operating System and version: **Windows 11 Pro 22H2. Version: 10.0.22621**
* Chocolatey version: **chocolatey version 1.2.1**

**Comment by jeansagi** [comment]
Not any plan yet?

**Comment by mkevenaar** [comment]
This should be fixed here: https://github.com/mkevenaar/chocolatey-packages/commit/d0fe41cc2490f8ce8e10c154ad46b379088ac230

**Comment by jeansagi** [comment]
Excellent!
