### ISSUE TITLE
SimilIDE Qt problem

### ISSUE THREAD

**Issue by Foadsf** [mkevenaar/chocolatey-packages#18]
## Expected Behavior
As reported [here](https://github.com/chocolatey/chocolatey-package-requests/issues/540#issuecomment-481411434) i tried installing the app through choco:

~~~
choco install simulide
~~~

## Current Behavior
 and I get the error message:

> ![Capture](https://user-images.githubusercontent.com/12762442/55830891-3fd56780-5b12-11e9-9161-8a2525433af3.PNG)

> This application failed to start because it could not find or load the Qt platform plugin "windows". Reinstalling the application may fix this problem. 

## Possible Solution

¯\\\_(ツ)\_/¯ 

## Steps to Reproduce (for bugs)

1. running simulide through the terminal
2. running the app through apps

## Context

🤔

## Your Environment

* Package Version used: 0.3.10
* Operating System and version: Windows 10 1809
* Chocolatey version: v0.10.13
* Install/uninstall gist: 🧐

Thanks for your support in advance.

**P.S.** An issue was also placed [here in the sourceforge repo of the software](https://sourceforge.net/p/simulide/discussion/bugs/thread/828b3b71b5/).

**Comment by mkevenaar** [comment]
@Foadsf Would you be able to update the issue with the template I have created?

**Comment by mkevenaar** [comment]
@Foadsf Could you try and start the software from `%CHOCOLATEYINSTALL%\lib\simulide\tools\SimulIDE_0.3.10_SR1-Win32\bin\simulide.exe`?

You can paste this in run or in explorer.

**Comment by Foadsf** [comment]
@mkevenaar Running the exe file worked. Thanks. However there is a `C:\ProgramData\chocolatey\bin\simulide.exe` which system refers to as the executable leading to this problem.

**Comment by mkevenaar** [comment]
@Foadsf Ah, so it's the shimgen file that is causing this.

I will add an ignore file to not create it then.

**Comment by mkevenaar** [comment]
@Foadsf A new version is pushed to the Chocolatey.org. The software will not be in the path, as it does not work at this moment.

Maurice
