### ISSUE TITLE
Upcoming major PowerToys installer changes

### ISSUE THREAD

**Issue by crutkas** [mkevenaar/chocolatey-packages#184]
We (PowerToys team) are about to shift our installer to enable both per-machine and per-user.

We believe this will impact the choco script.  @stefansjfw is the person on our side leading the shift to per-user and did the work to make WinGet work correctly.

we'd love to partner to be sure this script is functional when we release.

**Comment by stefansjfw** [comment]
Hi @mkevenaar,

The idea is to have 2 separate installers per release (per architecutre) - one per-user and one per-machine . The example release would look like this: https://github.com/stefansjfw/PowerToys/releases/tag/v0.72.1. Note: Installer names might be a subject to change.

The behavior we would like to achieve is following:

New users
- Default recommendation is per-user install.

For existing users on upgrade
- If unknown, defer to “Machine” as that would be a prior version scenario
- Per-machine upgrades to per-machine, per-user upgrades to per-user

(Once this work is done on our side, registry entry will be available to check which version is currently installed)

I gave WinGet a test with following manifests https://github.com/microsoft/winget-pkgs/compare/master...stefansjfw:winget-pkgs:stefan/test_powertoys?expand=1. WinGet is currently behaving as explained above.

Thanks. I'll be happy to help further if needed.

**Comment by crutkas** [comment]
@mkevenaar  we're getting ready to ship, chances are next week.  What can we do to help?

**Comment by TheCakeIsNaOH** [comment]
> Default recommendation is per-user install.

Chocolatey CLI by default is a machine wide program, and the packages it installs are then also machine wide. So a per-user installer would break anyone who needs to install PowerToys for multiple users on a machine, or anyone who uses a separate admin account to install things.

Chocolatey CLI can be installed per-user, but that is an unusual configuration used by a very small percentage of users (from what I have seen bug report wise).

Therefore, the machine installer should still probably be used exclusively.
