### ISSUE TITLE
powertoys: close powertoys window after installing

### ISSUE THREAD

**Issue by soredake** [mkevenaar/chocolatey-packages#189]
powertoys is automatically opens after installing, which i think is undesirable.

## Expected Behavior
powertoys window should be closed after installing.

## Current Behavior
powertoys window is not closed after installing.

## Possible Solution
Close powertoys window after installing.

## Steps to Reproduce (for bugs)

1. do `choco install -y powertoys`
2. powertoys window will open after installing

## Your Environment

* Package Version used: 0.68.1 
* Operating System and version: windows 11 pro
* Chocolatey version: 1.3.1
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
This is something what the PowerToys installer does. You could easily fix this with a post install hook, if you want.

Another option would be to reach out to the developers.

**Comment by soredake** [comment]
I realized that it's not worth it, as i use "useRememberedArgumentsForUpgrades" and with /NoStart remembered powertoys will not be restarted after upgrading, closing.
