### ISSUE TITLE
(winrar) allow to work when there are no checksums available.

### ISSUE THREAD

**Issue by mkevenaar** [mkevenaar/chocolatey-packages#20]
Currently WinRAR does not release all the translations in one go. Due to this, a lot of the translations are not available in the initial push.

**Comment by felipecassiors** [comment]
Winrar 3.90 x64 PT-BR is available, however the instalation still fails...

https://www.rarlab.com/rar/winrar-x64-590br.exe

**Comment by mkevenaar** [comment]
I have made a change to the helper function that should allow you to install when the checksums are not available in the package. I'll keep this open for a while to monitor

**Comment by mkevenaar** [comment]
I think this is now solved.
