### ISSUE TITLE
Zabbix 6.0 is LTS. Please continue to provide 6.0.X agents

### ISSUE THREAD

**Issue by noeplana** [mkevenaar/chocolatey-packages#210]
Zabbix 6.0 is LTS. Please continue to provide 6.0.X agents
Zabbix 6.4 is EOL in 31 December 2023. 6.4 is dead branch, no one should use it.

**Comment by anthonysomerset** [comment]
6.4 is by no means a dead branch... its still in support until the next version (7.0 which is also an LTS) comes out

but i agree - the latest Zabbix LTS should always be supported until its EOL date as well as the most current release as per zabbix lifecycle (https://www.zabbix.com/life_cycle_and_release_policy)

**Comment by noeplana** [comment]
@anthonysomerset So can you push build for 6.0.21 or 6.0.22?

**Comment by mkevenaar** [comment]
No, he cannot.

I have found where my script is breaking, but I am currently ill. Once I am better I'll fix this.

**Comment by mkevenaar** [comment]
This should be fixed now, a new package will be available on the repository once automated checks are complete
