### ISSUE TITLE
[microsoft windows terminal] could not list the latest verion 1.18.2681.0

### ISSUE THREAD

**Issue by rqx110** [mkevenaar/chocolatey-packages#212]
I saw the terminal has updated to latest version on https://community.chocolatey.org/packages/microsoft-windows-terminal/1.18.2681.0.
But while running `choco upgrade microsoft-windows-terminal -y` , it always show `microsoft-windows-terminal v1.17.11461.0 is the latest version available based on your source(s).`

**Comment by mkevenaar** [comment]
As the package is approved, this is most likely a caching issue. Please try again in a couple of hours
