### ISSUE TITLE
(thonny) Package is outdated and is a major version behind

### ISSUE THREAD

**Issue by AdmiringWorm** [mkevenaar/chocolatey-packages#220]
## Expected Behavior

I would expect the package to be up to date with the latest version available by the software developers.

## Current Behavior

The package [thonny](https://community.chocolatey.org/packages/thonny/3.3.13) is currently lagging several versions behind the software version, with the latest version available on their website being 4.1.3, while the Chocolatey Package currently uses 3.3.13.

## Possible Solution

If there is a problem with the automatic updater, to fix the update script to make it find the new version.

## Steps to Reproduce (for bugs)

1. Go to https://community.chocolatey.org/packages/thonny
2. Notice the latest version available there is 3.3.13
3. Go to the software site: https://thonny.org/
4. Notice the latest version is 4.1.3

## Context

I am currently in the process of trying out thonny with Raspberry Pi, and with a requirement of downloading Micropython. The older version of thonny can no longer download this software and requires to be updated to the latest version.

## Your Environment

* Package Version used: 3.3.13
* Operating System and version: Windows 11
* Chocolatey version: 2.2.2
* Install/uninstall gist: N/A (Not a problem with the install/uninstall)

**Comment by Dutcho** [comment]
I recognise the issue
The latest version of Thonny is now 4.1.4, but the Chocolatey package remains at 3.3.13.
@mkevenaar is listed as maintainer for the package. Can you please help, Maurice?

**Comment by Dutcho** [comment]
thanks!
