### ISSUE TITLE
(icloud) choco upgrade icloud failing 

### ISSUE THREAD

**Issue by dfranciscus** [mkevenaar/chocolatey-packages#23]
## Expected Behavior
icloud should install even if a previous version is installed.

## Current Behavior
Fails because bonjour is already installed.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)

1. install previous version of icloud
2. choco upgrade icloud

## Your Environment

* Package Version used:
* Operating System and version: Windows 10 1903
* Chocolatey version: 0.10.15
* Install/uninstall gist: https://gist.github.com/dfranciscus/1927c6a464bbd759430407085efaa4b3

**Comment by mkevenaar** [comment]
Hi, 

thank you for creating this issue.

**Comment by crkinard** [comment]
Not sure if my issue is the same as this one.

When installing the Bonjour64.msi errors out if Bonjour is already installed.
[iCloud_msi_install.log](https://github.com/mkevenaar/chocolatey-packages/files/3414963/iCloud_msi_install.log)
[chocolatey.log](https://github.com/mkevenaar/chocolatey-packages/files/3414964/chocolatey.log)

**Comment by dfranciscus** [comment]
Yep that’s mine too.

**Comment by crkinard** [comment]
Uninstall Bonjour from Programs and Features in the Control Panel then rerun "choco install icloud" and it installs with no issues.

Well it throws a 3010 exit code but thats just saying you need to reboot the computer.

**Comment by crkinard** [comment]
Actually I just noticed something. I dont think Apple is updating the installer gotten from the website anymore. It seems like the only way to get the current version (10.4.0.203) is from the Microsoft store.

Because of this not sure if fixing this issue is even needed.

**Comment by mkevenaar** [comment]
> It seems like the only way to get the current version (10.4.0.203) is from the Microsoft store.

As far as I can see, both versions should be the same. Could I ask you where you found that version number?

**Comment by crkinard** [comment]
After installing the version from the Microsoft Store should be able to get to an about box from the sign in window. I can post screenshots when I get home (didn't bring laptop to work).

**Comment by mkevenaar** [comment]
I have added exit code 1603 to the allowed exit code. This is not ideal but until I find an solution to detect the version of one part of the software and the version inside the MSI, I need to go this way.

**Comment by mkevenaar** [comment]
I think this is now solved.
