### ISSUE TITLE
(exiftool) Emebed binary into package

### ISSUE THREAD

**Issue by pauby** [mkevenaar/chocolatey-packages#230]
## Expected Behavior
As per [this discussion](https://github.com/orgs/chocolatey/discussions/299), the software author seems to be having issues with the binary downloaded from their website. As the license allows the binary to be embedded, it would solve this issue if it was.

## Current Behavior
Binary is downloaded from the website each time.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment

* Package Version used: 12.76.0
* Operating System and version: N/A
* Chocolatey version: N/A
* Install/uninstall gist: N/A

**Comment by mkevenaar** [comment]
A new version has been pushed: https://community.chocolatey.org/packages/exiftool/12.76.0.20240210
