### ISSUE TITLE
Error while upgrading IrfanView from 4.66.0 to 4.67.0

### ISSUE THREAD

**Issue by Trellmor** [mkevenaar/chocolatey-packages#235]
Upgrading irfanview from 4.66.0 to 4.67.0 shows error "You cannot call a method on a null-valued expression."

## Expected Behavior
Upgrade to IrfanView 4.67.0

## Current Behavior
Chocolatey v0.11.3
Upgrading the following packages:
irfanview
By upgrading, you accept licenses for the packages.

You have irfanview v4.66.0 installed. Version 4.67.0 is available based on your source(s).
Progress: Downloading IrfanView 4.67.0... 100%

IrfanView v4.67.0 [Approved]
irfanview package files upgrade completed. Performing other installation steps.
ERROR: You cannot call a method on a null-valued expression.
The upgrade of irfanview was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanview (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

2024-04-18 11:37:42,637 24244 [ERROR] - ERROR: You cannot call a method on a null-valued expression.
2024-04-18 11:37:42,800 24244 [ERROR] - The upgrade of irfanview was NOT successful.
2024-04-18 11:37:42,801 24244 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.

## Steps to Reproduce (for bugs)
1. Have irfanview 4.66.0 installed
2. Run choco upgrade irfanview

## Your Environment

* Package Version used: irfanview 4.66.0 installed, tried to upgrade to 4.67.0
* Operating System and version: Windows 10 22H2 Build 19045.4291
* Chocolatey version: v0.11.3

**Comment by Trellmor** [comment]
I had an old version of chocolatey installed, but the problem persists after upgrading chocolatey to version 2.2.2

choco upgrade irfanview
Chocolatey v2.2.2
Upgrading the following packages:
irfanview
By upgrading, you accept licenses for the packages.

You have irfanview v4.66.0 installed. Version 4.67.0 is available based on your source(s).
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'irfanviewplugins 4.66.0 constraint: irfanview (>= 4.66.0)'
Progress: Downloading IrfanView 4.67.0... 100%

irfanview v4.67.0 [Approved]
irfanview package files upgrade completed. Performing other installation steps.
ERROR: You cannot call a method on a null-valued expression.
The upgrade of irfanview was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanview (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

C:\Users\CPATRD>choco upgrade irfanviewplugins
Chocolatey v2.2.2
Upgrading the following packages:
irfanviewplugins
By upgrading, you accept licenses for the packages.
irfanviewplugins v4.66.0 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by mkevenaar** [comment]
I am unable to reproduce this on multiple machines

Would you please try uninstalling and then installing Irfanview and irfanviewplugins? 
You may need to run `choco install irfanviewplugins --version=4.67.0` to install the latest version

Thanks

**Comment by Trellmor** [comment]
Thank you, uninstalling irvfanview and irfanviewplugins and reinstalling them solved it. Installing 4.66.0 and then upgrading also seems to work now. Not sure what went wrong before, maybe something with my outdated chocolatey version.
