### ISSUE TITLE
(jetbrainstoolbox) update fails with timeout

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [mkevenaar/chocolatey-packages#236]
## Expected Behavior
Should update without errors

## Current Behavior
installation times out 

## Steps to Reproduce (for bugs)
1. `choco upgrade jetbrainstoolbox`

## Your Environment
* Package Version used: 2.3.0.30876
* Operating System and version:  Windows 23H2 10.0.22631.0
* Chocolatey version: 2.2.2
* Install/uninstall gist:
```
Chocolatey v2.2.2
Upgrading the following packages:
jetbrainstoolbox
By upgrading, you accept licenses for the packages.

You have jetbrainstoolbox v2.2.3.20090 installed. Version 2.3.0.30876 is available based on your source(s).
Progress: Downloading jetbrainstoolbox 2.3.0.30876... 100%

jetbrainstoolbox v2.3.0.30876 [Approved]
jetbrainstoolbox package files upgrade completed. Performing other installation steps.
The package jetbrainstoolbox wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing jetbrainstoolbox...
Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
The upgrade of jetbrainstoolbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\jetbrainstoolbox\tools\chocolateyinstall.ps1'.
 See log for details.
 Unsuccessful operation for jetbrainstoolbox.
  Rollback to previous version (package files only)?([Y]es/[N]o):
```

**Comment by Schroedingers-Cat** [comment]
Also affected by this over the last days.

**Comment by FibreFoX** [comment]
Can confirm this being a big problem.

I've tried executing the downloaded installer "by hand", does install okay, so maybe something inside the installer has changed regarding the "no GUI" mode. Does anyone know how to report this to jetbrains themselves?

**Comment by mkevenaar** [comment]
I have delisted version 2.3.0.30876.

Bug reports can be posted here: https://youtrack.jetbrains.com/issues/TBX @FibreFoX

**Comment by FibreFoX** [comment]
Issue seems to be still present with 2.3.1.31116

**Comment by FibreFoX** [comment]
It was confirmed that the installer had this bug: https://youtrack.jetbrains.com/issue/TBX-3219/Toolbox-App-silent-install#focus=Comments-27-9799256.0-0

Looking at the changes, it might get fixed soon with a new version:
![Screenshot 2024-05-17 093444](https://github.com/mkevenaar/chocolatey-packages/assets/1042579/d6465a9a-d1dc-471c-95fe-7bb37e43d9b8)

**Comment by FibreFoX** [comment]
Current version `2.3.2.31487` of the installer (directly fetched from their website) still contains the bug. I will wait for 2.4.x to check if that fixes something

**Comment by FibreFoX** [comment]
`2.4.0.32175` is finally released, which contains the bugfix. Will report back once its available via chocolatey, to confirm this bug being fixed

**Comment by FibreFoX** [comment]
Bug still exists, because the new installer switched to new arguments: `/s /headless` instead of `/S /ju` (as shown in the description https://youtrack.jetbrains.com/issue/TBX-3219/Toolbox-App-silent-install)
