### ISSUE TITLE
JetBrains Toolbox v2.3 not on Chocolatey

### ISSUE THREAD

**Issue by mu88** [mkevenaar/chocolatey-packages#238]
Dear @mkevenaar,

Thank you for providing the JetBrains Toolbox on Chocolatey 🙏🏻

I was wondering why the latest version `2.3.0` does not appear on [Chocolatey](https://community.chocolatey.org/packages/jetbrainstoolbox#versionhistory), although you already changed [the sources](https://github.com/mkevenaar/chocolatey-packages/commit/d088411f5eb6313c3a4aee9963dfa4cb51b85fbb) 🤔

Best regards!

**Comment by mkevenaar** [comment]
Hey @mu88 See https://github.com/mkevenaar/chocolatey-packages/issues/236
