### ISSUE TITLE
ZeroTier-One Chocolatey package fails

### ISSUE THREAD

**Issue by AIVAS001** [mkevenaar/chocolatey-packages#240]
ZeroTier-One package fails upgrade

"Progress: Downloading zerotier-one 1.14.0... 100%

zerotier-one v1.14.0 [Approved]
zerotier-one package files upgrade completed. Performing other installation steps.
Installing zerotier-one...
WARNING: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'zerotier-one' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\zerotier-one\tools\ZeroTier%20One.msi" /qn /norestart /l*v "C:\Users\rjp\AppData\Local\Temp\chocolatey\zerotier-one.1.14.0.log" ] was not successful. Exit code was '1619'. Exit code indicates the following: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'zerotier-one' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The upgrade of zerotier-one was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zerotier-one\tools\chocolateyinstall.ps1'.
 See log for details."

Possible cause? Download link for MSI package has space in file name which has been re-encoded to "%20". Reverting "%20" to " " should likely rectify issue. May require escaping the space character to prevent percent-encoding.

**Comment by itmokel** [comment]
Small workaround for a successful upgrade:

"choco upgrade zerotier-one"
Before pressing "y" go to "C:\ProgramData\chocolatey\lib\zerotier-one\tools" and rename "ZeroTier One.msi" to "ZeroTier%20One.msi"
Press "y" and the installation goes through
