### ISSUE TITLE
(slack) outdated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [mkevenaar/chocolatey-packages#251]
## Expected Behavior

That Slack v4.39.89 would be available to install

## Current Behavior

Slack v4.38.127 is available

## Possible Solution

Looks like the updater is broken because there is no longer a 32-bit build for Slack v4.39.x
https://slack.com/help/articles/4426294050451-Slack-feature-retirements#announcements.

## Steps to Reproduce (for bugs)
1. `choco upgrade slack`

## Context

Slack is outdated.

## Your Environment

* Package Version used: 4.38.127
* Operating System and version: N/A
* Chocolatey version: N/A
* Install/uninstall gist: N/A

**Comment by mkevenaar** [comment]
Fixed with #252
