### ISSUE TITLE
0.3.2142.0 microsoft-windows-terminal - Fails To Install

### ISSUE THREAD

**Issue by Spinarooni** [mkevenaar/chocolatey-packages#26]
## Expected Behavior
Install should be successful.

## Current Behavior
Install fails with a missing dependency error:

```
Windows cannot install package Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: Microsoft.VCLibs.140.00_14.0.24123.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.24123.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.25426.0_x64__8wekyb3d8bbwe
Microsoft.VCLibs.140.00_14.0.25426.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.26706.0_x64__8wekyb3d8bbwe
Microsoft.VCLibs.140.00_14.0.26706.0_x86__8wekyb3d8bbwe}
```

## Possible Solution
Tried installing the VC++ Redist Update 3 for 2015: https://www.microsoft.com/en-us/download/details.aspx?id=53587.  The version installed by this update was not high enough as apparently the dependency needed must be 14.0.27323.0 or higher.  I have not been able to locate what redist package contains this version though.  

## Your Environment

* Package Version used: 0.3.2142.0
* Operating System and version: Win 10 Build 1903
* Chocolatey version: 0.10.15

**Comment by mkevenaar** [comment]
@Spinarooni Thanks for creating this issue, I already added the dependency here: https://github.com/mkevenaar/chocolatey-packages/commit/6a55e0b198eb1e97c88309b0632c401606a71fa6

**Comment by mkevenaar** [comment]
The next version will include the dependency.

**Comment by Spinarooni** [comment]
@majkinetor As an FYI, I already had that vcredist140 package installed and it still failed with a missing dependency error when I tried to install the microsoft-windows-terminal package.

![image](https://user-images.githubusercontent.com/331866/62549350-51b3e680-b836-11e9-8dae-a736d16ce892.png)

Not sure if I missed something.

**Comment by mkevenaar** [comment]
@Spinarooni Have you tried restarting your computer? (and I think you mis-tagged me)

**Comment by Spinarooni** [comment]
@mkevenaar I tried removing the vcredist140 package and reinstalling it then rebooting.  Rebooted and tried to install the microsoft-windows-terminal package and it failed again:

```
Windows cannot install package Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.V
CLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.27323.0, al
ong with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.
Windows cannot install package Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.V
CLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.27323.0, al
ong with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.24123.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00
_14.0.24123.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.25426.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.25426.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.26706.0_x64__8we
kyb3d8bbwe Microsoft.VCLibs.140.00_14.0.26706.0_x86__8wekyb3d8bbwe}
```
