### ISSUE TITLE
(intel-dsa) Outdated, Incorrect Links, and Not Present In Repository

### ISSUE THREAD

**Issue by JPRuskin** [mkevenaar/chocolatey-packages#267]
## Expected Behavior

intel-dsa should be present in this repository, and the package on the CCR should be up to date with valid links to package source etc.

## Current Behavior

The intel-dsa package is outdated, and is still showing links to the previous maintainer's package source and patreon.

## Possible Solution

I feel cheeky even typing out this solution. 😅 

I'd happily submit a PR, but I imagine there's a few things that need to be done to match your standards rather than just pulling the existing code in.

## Steps to Reproduce (for bugs)

See: https://community.chocolatey.org/packages/intel-dsa

## Context

A user has been attempting to get a latest version available on the repository in various ways, and may already have updated code for this.

## Your Environment

N/A

**Comment by mkevenaar** [comment]
Hi @JPRuskin feel free to create a PR

**Comment by JPRuskin** [comment]
Hopefully that looks alright!

I need to spin up a machine with an older version of dotnet to make sure I was okay to remove the dotnet 4.7 dependency.

I checked that the EULA-acceptance doesn't happen any more, though, and the install and uninstall succeed silently without user input, so removed the other dependency.
