### ISSUE TITLE
Automatic Update for Samsung Magician is Broken.

### ISSUE THREAD

**Issue by nykBM** [mkevenaar/chocolatey-packages#271]
## Expected Behavior
Samsung Magician Package V8.2 is updated and release to the community

## Current Behavior
Samsung Magician Package V8.0 is only available.

## Possible Solution
Update package with new file at https://semiconductor.samsung.com/consumer-storage/support/tools/

## Steps to Reproduce (for bugs)

Go to Chocolately Community page for Samsung Magician and new version is not released.

## Context
Computer is not updated to the latest released software.

## Your Environment
Windows 11
Chocolately V2.3.0
Samsung Package V8.0

**Comment by asheroto** [comment]
According to [this comment](http://disq.us/p/2z5cjkh), @virtualex-itv may be aware of the problem, but I'm not sure if there was any resolution to the matter. It appears that the package hasn't been updated in some time.

Since version 8.0, version 8.1 and version 8.2 have been released. I understand this is an AU package but it appears it's still broken.

**Comment by virtualex-itv** [comment]
Yes we've been aware of the issue but so far has not been an easy fix as it is unrelated to how it's configured for AU.  I believe it's something to do with the checksum values not matching but we'll have to do some further digging.  @mkevenaar is the true owner of the package so he needs to investigate further, time permitting.

**Comment by asheroto** [comment]
Looks like #246 might be related, but the date looks like it was back in June and is a draft.

I spent a few hours re-writing an testing. Samsung makes it a real pain as they don't allow silent installs!

Opened PR #275.

**Comment by virtualex-itv** [comment]
This has now been fixed in [PR #246](https://github.com/mkevenaar/chocolatey-packages/pull/246).
