### ISSUE TITLE
(lastpass) SHA-256 checksum incorrect

### ISSUE THREAD

**Issue by grnassar** [mkevenaar/chocolatey-packages#30]
For some reason, the chocolateyInstall.ps1 file seems to have the SHA-256 hash of LastPass (x64) 4.1.57:
9427DCC285BF574C7AAB03E998E7C2062F0A3E62619048062BF956EBCF1B48FA
rather than the hash of version 4.33: (would appreciate third-party confirmation, of course!)
2401C795E7584C3A185E221CBA77DBB422A82AA4CE97936534066F5EE9C79005

This causes installs/updates to fail, of course, unless ignore-checksums is used.

## Expected Behavior
Installer would download LP x64 4.33, confirm the checksum and install

## Current Behavior
Installer fails after download with checksum error, listing the checksums above as what it claims are "right" and "wrong", respectively

## Possible Solution
Update checksum in chocolateyInstall.ps1 file

## Steps to Reproduce (for bugs)
Attempt to install or upgrade lastpass (x64).  Status of x86 unknown.

**Comment by mkevenaar** [comment]
Hi @grnassar I have kicked the build to upload the lastpass package again. This should be available soon.

Please let me know if this works for you.

**Comment by cprivite** [comment]
This has reoccurred. Now the hash should be Is broke again as of 9/25/19. SHA hash doesn't match the actual download.

**Comment by mkevenaar** [comment]
@cprivite I have just pushed a new version of the package. Should be correct now.
