### ISSUE TITLE
(Lastpass) Not actually installing lastpass

### ISSUE THREAD

**Issue by cprivite** [mkevenaar/chocolatey-packages#32]
## Expected Behavior
Lastpass gets installed.

## Current Behavior
Lastpass doesn't get installed.

## Possible Solution
Can you at least verify it works on your machine? 

## Steps to Reproduce (for bugs)
1) Remove lastpass from all browsers, choco, and add/remove programs
2) Reboot
3) Install lastpass via chocolatey (choco install lastpass --ignore-checksum)
4) Open browsers and see there's no lastpass.

## Your Environment
* Package Version used: 4.33.0.20190917
* Operating System and version: Microsoft Windows [Version 10.0.18362.356]
* Chocolatey version: v0.10.15

**Comment by mkevenaar** [comment]
@cprivite I don't think this installs lastpass in your browser. There are separate packages for that. 
See https://chocolatey.org/packages?q=tag%3Alastpass

**Comment by cprivite** [comment]
I must admit, I'm extremely confused by your response. That's literally all lastpass is, a browser plugin. Look at the silent install arguments if you don't believe me: "'-si --userinstallie --userinstallff --userinstallchrome'" It's literally stating the browsers to install the plugin into. I'm sorry, but do you actually use lastpass?

**Comment by mkevenaar** [comment]
Sorry you are correct :) I have reopened the issue again.

I am currently not using lastpass. Could you share what browsers you have tested this with?

**Comment by cprivite** [comment]
That said, it's possible this is an issue on lastpass's side. They have had a very bad track record lately. 

I've tested this with chrome and firefox, but I have not tested with the new version you updated the checksum for, I will try to do so tonight and get back to you. Thanks for re-opening. Is there a history for this package that I should know before jumping to any conclusions about how it "should" work? Like was this particular package added to only install the lastpass for applications thing (something that's technically not part of the browser, but that no one tends to actually use cause it's awful) or something?

**Comment by mkevenaar** [comment]
I believe it should work as you have expected it to do. If you don't get it working again, please let me know and I'll try to get it working

**Comment by cprivite** [comment]
I think it's working right now. I'll close for now and reopen a new issue if I see future problems.
