### ISSUE TITLE
SQL2014.ClrTypes hash failures

### ISSUE THREAD

**Issue by sd3z** [mkevenaar/chocolatey-packages#33]
The https://chocolatey.org/packages/SQL2014.ClrTypes package SHA256 is failing has match

## Expected Behavior
`choco install sql2014.clrtypes -y  should work with no errors`

## Current Behavior
Error message received
'C:\Users\Administrator\AppData\Local\Temp\chocolatey\SQL2014.ClrTypes\12.1.4100.1\SQLSysClrTypes.msi' did not meet 'D264B0B4D8E503C2638C18F09FF74F895DA92A9984D2B7C5D6192A6A22FA3C41' for checksum type 'sha256'.

## Possible Solution
Update the script with the new SHA256 checksums, alternatively to get around it is 
`choco install sql2014.clrtypes -y --checksum64 74CB1BC8216B24ACFBC643EA7555FC7D6067DFD39B7316E79203552C36282C8F -checksum 5CA2CC72AA5B9D02014958A8BF664676672DE7D10EF4F4BD2658301210541867`

## Steps to Reproduce (for bugs)
` choco install sql2014.clrtypes -y  `

**Comment by mkevenaar** [comment]
Thanks for reporting this, this should be fixed here: https://github.com/mkevenaar/chocolatey-packages/commit/b734cd629a6f5a886b7df90b9eab490ca443057c

A new package will be pushed soon.
