### ISSUE TITLE
iCloud 10.15 Fails on install

### ISSUE THREAD

**Issue by ljferdinand** [mkevenaar/chocolatey-packages#36]
## Expected Behavior

iCloud Installation complete

## Current Behavior

MSI (s) (84:58) [10:33:18:172]: Product: iCloud -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action RuniCloudUpgrade, location: C:\Program Files (x86)\Common Files\Apple\Internet Services\, command: C:\Program Files (x86)\Common Files\Apple\Internet Services\iCloud.exe /upgrade 

Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action RuniCloudUpgrade, location: C:\Program Files (x86)\Common Files\Apple\Internet Services\, command: C:\Program Files (x86)\Common Files\Apple\Internet Services\iCloud.exe /upgrade 

## Steps to Reproduce (for bugs)

1. choco install icloud -y -f
2.
3.
4.

## Context
This error does not occur with the iCloudSetup.exe

## Your Environment

* Package Version used: 
Apple iCloud 7.15.0.10
* Operating System and version: Windows 10 v1809, 1903
* Chocolatey version: .10.15
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
Could you please share the parts of your chocolatey.log as I can’t reproduce this? Please use a gist for this.
