### ISSUE TITLE
Pulumi 1.5.0 and 1.5.1

### ISSUE THREAD

**Issue by lukehoban** [mkevenaar/chocolatey-packages#37]
The Pulumi package doesn't appear to have been automatically updated for the `1.5.0` or `1.5.1` releases earlier this week.

https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#151-2019-11-06

**Comment by mkevenaar** [comment]
It seems that they are not pushing due to https://github.com/chocolatey/chocolatey.org/issues/613

**Comment by lukehoban** [comment]
Curious - is there anything we can do to manually publish these to workaround the upstream issue?

**Comment by mkevenaar** [comment]
The packages have been pushed.
