### ISSUE TITLE
(UltraVNC) Why has the X64 been removed?

### ISSUE THREAD

**Issue by jpluimers** [mkevenaar/chocolatey-packages#42]
In commit https://github.com/mkevenaar/chocolatey-packages/commit/82e0cb35626e765479b44c75cc6d155bbd5d4836#diff-4 the X64 hash of UltraVNC has been removed.

Why is that?

I just verified the manual downloads from the UltraVNC site with `wget --referer=https://www.uvnc.com/ --mirror` based ones and they indeed match (and of course both files have their own hash):

```
21d4d4a35cb7111b273b18b67db8cf5b8e12e44178796034519eed0479039c72 www.uvnc.eu/download/1230/UltraVNC_1_2_30_X86_Setup.exe
5eaa8ce5d6d3abb2bfcc392d6931a9d68ecd9c77a03328d266bbdb558910ccf0 www.uvnc.eu/download/1230/UltraVNC_1_2_30_X64_Setup.exe
```

**Comment by mkevenaar** [comment]
Hi @jpluimers 
My mistake :) I am currently working on a fix for that.

**Comment by jpluimers** [comment]
No problem: That's what we are humans for (:

Discuss seems to ping between pending/spam/allow on my account, so I thought posting it here (knowing GitHub is way more predictable in posting issues).

Do you want me to post the https://disqus.com/home/discussion/chocolatey/chocolatey_gallery_ultravnc_11800/#comment-4745913819 on the various 404 URLs as issue here as well?

**Comment by mkevenaar** [comment]
@jpluimers No I have seen it :) Thanks, I am working on embedding the software in the package. The License is GPL as shown here: https://www.uvnc.com/downloads/ultravnc/128-download-ultravnc-1230.html

**Comment by jpluimers** [comment]
Great!

I tried searching https://www.google.com/search?q=license+site%3Auvnc.com but could not find one.

So the license URL is now http://www.gnu.org/licenses/gpl.html (:

**Comment by mkevenaar** [comment]
I am working on getting it embedded. I will get there, but takes a while. Anyway: Bedankt voor de hulp :)

**Comment by mkevenaar** [comment]
@jpluimers A new version has been pushed with the files embedded into the package:
https://chocolatey.org/packages/ultravnc/1.2300.0.20200105#files

**Comment by jpluimers** [comment]
Thanks. Works splendid.

```
You have ultravnc v1.2240.0.20190403 installed. Version 1.2300.0.20200105 is available based on your source(s).
Progress: Downloading ultravnc 1.2300.0.20200105... 100%

ultravnc v1.2300.0.20200105 [Approved]
ultravnc package files upgrade completed. Performing other installation steps.
Installing 64-bit ultravnc...
ultravnc has been installed.
  ultravnc can be automatically uninstalled.
 ShimGen has successfully created a shim for UltraVNC_1_2_30_X86_Setup.exe
 The upgrade of ultravnc was successful.
  Software installed to 'C:\Program Files\uvnc bvba\UltraVNC\'
```

**Comment by Neustradamus** [comment]
Dear all, @mkevenaar,

I have done a ticket to have a fix about bad UltraVNC version numbers in Chocolatey:
- https://github.com/mkevenaar/chocolatey-packages/issues/276

In more, I have done a ticket one year ago about 1.4.3.6:
- https://github.com/mkevenaar/chocolatey-packages/issues/222
