### ISSUE TITLE
(mongodb) Remove or allow skipping starting of mongodb database service

### ISSUE THREAD

**Issue by TraGicCode** [mkevenaar/chocolatey-packages#47]
## Expected Behavior

I should be allow to install mongodb import/export tools only, using the msi, without installing the mongodb database that runs as a windows service.  This WOULD work with the following chocolatey puppet code.

```
package { 'mongodb':
    ensure   => '4.2.3',
    # ensure => 'absent',
    install_options => [
      '--override',
      '--installArgs',
      '"',
      '/qn',
      '/norestart',
      'ADDLOCAL="ImportExportTools"',
      '"'
    ],
    provider => 'chocolatey',
  }
```

## Current Behavior

The installation of ONLY the import/export tools works with the above code BUT since the chocolateyinstall.ps1 calls Start-Service and Get-Service it fails!

## Possible Solution

Either removing the Start-Service and Get-Service calls OR allowing the ability to pass a package parameter to skip the windows service checks.

**Comment by mkevenaar** [comment]
Hi @TraGicCode,

I see what you are trying to do here. This package was not designed to only install ImportExportTools.

However, I think this could be implemented. Are you willing to create a PR for this?

**Comment by TraGicCode** [comment]
Hey @mkevenaar ,

Yea I could give it a shot when I get some spare time.  What do you think would be a good approach for this? Are you aware of any patterns other packages use?

**Comment by mkevenaar** [comment]
@TraGicCode I would go with package parameters. 

By default the end-result should not be changed.
I believe when I started with the package, the MSI would not start the service. I would have expected that from the installation and therefore I added this.

Hope this helps,

Maurice

**Comment by TraGicCode** [comment]
Hey @mkevenaar ,

By Default, using the latest msi for mongodb it ensures the service is started after installation if service installation is selected ( which is the default ).  Therefore the simplistic approach at this point seems to simply remove the powershell code for starting the service.  

Can you let me know if you agree with this?  If so i can create a pull request to update the chocolatey powershell scripts.

Thanks!

**Comment by mkevenaar** [comment]
@TraGicCode I agree.
