### ISSUE TITLE
(nginx) Install/upgrade to a consistent directory

### ISSUE THREAD

**Issue by flcdrg** [mkevenaar/chocolatey-packages#49]
As mentioned in package comments for nginx, even when using the `/installLocation` parameter, the actual directory that nginx ends up in changes depending on the version number.. eg. `C:\nginx\nginx-1.17.9`.

I suspect this is caused by the unzipping using the zip filename.

Probably should preserve existing config during an upgrade

**Comment by mkevenaar** [comment]
Hi @flcdrg, thanks for creating this issue. Are you willing to create a PR for this as well?

**Comment by flcdrg** [comment]
yeah, I think so. 

David

**Comment by mkevenaar** [comment]
@flcdrg Thank you!

**Comment by JasonMeudt** [comment]
Any chance this could be implemented before the next release?

**Comment by flcdrg** [comment]
Been looking into this, and it's not as easy as I'd first thought. 7zip (which Chocolatey is using to unzip) doesn't seem to have a native way to extract the nginx-1.7.9 subdirectory from inside the .zip and put just the contents of that that into c:\nginx.

I could just do a recursive move or copy after the unzip has completed. What I'm wondering is how this should work... overwrite everything except config files?

**Comment by mkevenaar** [comment]
> I could just do a recursive move or copy after the unzip has completed. What I'm wondering is how this should work... overwrite everything except config files?

I think that could work. More/less the same I do for the `mysql` and  `mariadb.portable` packages.

**Comment by JasonMeudt** [comment]
While this was marked stale/wontfix, before I test that on installing, would someone verify that this is indeed still installing to the version number foldering structure. eg. C:\nginx\nginx-1.xx.x?

**Comment by flcdrg** [comment]
It was the last time I tried. Sorry I wasn't able to get further with the fix. The incentive to fix it has now reduced as I've changed roles.

**Comment by reijerh** [comment]
Yeah and upgrades seem to end up in the default folder.
