### ISSUE TITLE
(samsung-magician) Wrong checksum for version 6.1.0

### ISSUE THREAD

**Issue by Fooughhy** [mkevenaar/chocolatey-packages#52]
## Expected Behavior

The install should succeed without errors.

## Current Behavior

The installation process throws the following error:

> Checksum for 'C:\Users\fough\AppData\Local\Temp\chocolatey\samsung-magician\6.1.0\samsung-magicianInstall.zip' di
d not meet '9daeed4fdd5b4492442c706ee71d305b00824e716415fb616235e00174403dfd' for checksum type 'sha256'. Consider passi
ng the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less sec
ure option is to pass --ignore-checksums if necessary.
The upgrade of samsung-magician was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\samsung-magician\tools\chocolateyInstall.ps1'.
 See log for details.

Then fails.

## Possible Solution

Fix the link to point to the new files and fix the checksum.

## Steps to Reproduce (for bugs)

1. Install Samsung Magician 6.0.0 through Chocolatey
2. Update to version 6.1.0
OR
1. Install Samsung Magician 6.1.0, as I would imagine this would produce the same error.

## Your Environment

* Package Version used: 6.1.0
* Operating System and version: Windows 10, 1909
* Chocolatey version: 0.10.16
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
I think you are hitting their rate limiting mechanism.

See: https://chocolatey.org/packages/samsung-magician#comment-4877039863

If you check the downloaded file, it will probably a couple of bytes. 

I can't fix this as I am not allowed to embed the software.

**Comment by Fooughhy** [comment]
Ok, it's 55kB but I guess the point still stands. Thank you! Will have to wait then I guess...

**Comment by leonghui** [comment]
Is the package using the correct URL? I couldn't find the link `http://ssd.samsungsemi.com/ecomobile/ssd/update8.do?fname=/Samsung_Magician_Installer.zip` when I navigated to the download page `https://www.samsung.com/semiconductor/minisite/ssd/download/tools/` manually.

Instead, the download page gave a link with an AWS domain (possible geo-located?). I replaced the AWS domain with `www.samsung.com` and it worked fine. I have been monitoring the following URL for 2 weeks now and it is still active:
`https://www.samsung.com/semiconductor/global.semi.static/SAMSUNG_SSD_v6_1_0_200310/SW/675B9E5CD0C5F99B41D766B27C8E0055C3909ECE3AA2FB6B74A2A1EAC1BAC402/Samsung_Magician_Installer.zip`

**Comment by jmoralesv** [comment]
Hi all,
I found the same issue, this time with version 6.3.0. The URL used by the Chocolatey package resolves to an error. In the Samsung site, https://www.samsung.com/semiconductor/minisite/ssd/download/tools/, the current URL uses an Azure URL, https://p6wrew7f.azureedge.net/magician/202102/20210209_Magician_6.3_r26c7b0eafa6.zip/REAL/Samsung_Magician_Installer_Official_6.3.0.300.zip

I think Samsung has changed the URL, would this need to be addressed in a future update for this package?

**Comment by guenam** [comment]
The issue has been going on for quite a while now. It looks like the maintainer has given up or is too busy.

**Comment by mkevenaar** [comment]
Nope, I can't fix the policy of Samsung. 

Also you are reporting on a closed issue.

Please open a new issue.
