### ISSUE TITLE
Mysql loses admin access after restarting the computer

### ISSUE THREAD

**Issue by spacedog4** [mkevenaar/chocolatey-packages#53]
## Bug
After installing mysql, all works fine, but after restarting the computer, I have to manually right click on mysql and give admin access so it doesn't throw me an error saying that the access was denied to root@localhost

## Error
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost'

## Possible Solution
Maybe an chmod or chown on the file or something like that should resolve the problem

## Temporary solution
a) Reinstall mysql, it keeps the database
b) Access mysql folder and forces mysql to open as an administrator (for some reason, after restarting the computer it loses the administrator permition and you need to do it again)

## Steps to Reproduce (for bugs)
1. Install mysql throu `choco install mysql`
2. Log in though `mysql -uroot -proot`
3. Restart the computer
4. Try to log in again

## Your Environment

* Package Version used: 8.0.2
* Operating System and version: Windows 10 Pro 1809
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
Hi @spacedog4,

Can you please fill in the template part of Your Environment? I need this to verify some stuff.

Can you also please add the error message you are getting? That way I can try to detect if it is an issue with the package or something else.

**Comment by spacedog4** [comment]
Hi @mkevenaar,

I apologize, i didn't so those fields, I added then, but I don't know gist, it might be some software for linux or mac.

I also added a "Temporary Solution" section where how do I prevent the error temporarly

**Comment by mkevenaar** [comment]
Hi @spacedog4 

By default the package installs without any credentials. I am not updating or changing any credentials. I am currently not able to reproduce this issue.

**Comment by spacedog4** [comment]
@mkevenaar this is probably an specific issue related to my computer I realized that sometimes I need to remove the administrator permission, like an update on the exe saying for windows "Hey, this file is here and it exists okay?!?!?!?"

So I'll close this issue, thank you anyway
