### ISSUE TITLE
(clion-ide) package doesn't upgrade but installs all versions side by side

### ISSUE THREAD

**Issue by Schroedingers-Cat** [mkevenaar/chocolatey-packages#54]
## Expected Behavior
A package upgrade should remove the previous version and leave only the current version on the computer.

## Current Behavior
Currently, all versions of a package remain on the computer after an upgrade of the package. This means that users installing clion will end up wasting a lot of hard disk space.

## Possible Solution
A solution would be to remove the currently installed version of clion before installing the latest version.

## Steps to Reproduce (for bugs)
1. Install an older clion package via chocolatey
2. Upgrade through some versions
3. Check `C:\Program Files (x86)\Jetbrains`
It will look like this: http://disq.us/p/29bbtta

## Your Environment

* Package Version used: 2019 through 2020
* Operating System and version: Windows 10 1909
* Chocolatey version: 0.10.15
* Install/uninstall gist: ?

**Comment by Schroedingers-Cat** [comment]
Maintainer?

**Comment by mkevenaar** [comment]
@Schroedingers-Cat Thanks for submitting this issue, I will have a look at this.

**Comment by mkevenaar** [comment]
@Schroedingers-Cat this has been fixed in git just now. It will take 2 new packages before this comes into play. Until then, please uninstall previous versions manually.
