### ISSUE TITLE
(microsoft-windows-terminal) Package installs the pre-release version instead of the stable version

### ISSUE THREAD

**Issue by ptanmay143** [mkevenaar/chocolatey-packages#55]
## Expected Behavior
The chocolatey package `microsoft-windows-terminal` should install the latest stable version of the terminal from the releases page. You can see the version v1.1.1671.0 is tagged as pre-release.

## Current Behavior
Currently, it disregards the GitHub releases tag and install the one on the top, no matter if it is the pre-release version or the stable release version.

## Possible Solution
Relying on the tag of the GitHub release for getting the package would be a better option. The link (https://github.com/microsoft/terminal/releases/latest) should always point to the latest stable version (currently v1.0.1401.0) even if the upstream updates the package version.
Secondly, a different chocolatey package `microsoft-windows-terminal-beta` could be made that would track only the pre-release versions of this terminal.

## Steps to Reproduce (for bugs)
I'm not sure how to specify the steps to reproduce. I believe the explanation above is enough but if you think this step is absolutely necessary, please guide me on how would I properly write the steps to reproduce.

## Context
As I plan to use the terminal very frequently, I would appreciate if it was running a stable version rather than a pre release version. I hope I am making sense here.

## Your Environment
* Package Version used: v1.1.1671.0
* Operating System and version: Microsoft Windows 10 Build 2004
* Chocolatey version: 0.10.15
* Install/uninstall gist: https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/microsoft-windows-terminal/tools (I'm not again sure what this gist means, but I think you meant to refer to the link to the install uninstall scripts in the repository.)

## Notes
I would be happy to send a PR if you could guide me how the install scripts are built.

**Comment by ptanmay143** [comment]
Moreover, I had the v1.0.1401.0 already installed and then I ran a chocolatey upgrade. This caused the start menu to have two entries for Microsoft Terminal.
![image](https://user-images.githubusercontent.com/39222830/85199010-2335e180-b30a-11ea-807d-79f8376ff4a8.png)
I suspected this was due to the pre-release version (also called as Preview in Windows) having a different Appx package name. So I ran `Get-AppxPackage` and I actually did saw two entries for Windows Terminal.
```
Name              : Microsoft.WindowsTerminal
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.1401.0
PackageFullName   : Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminal_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Name              : Microsoft.WindowsTerminalPreview
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.1.1671.0
PackageFullName   : Microsoft.WindowsTerminalPreview_1.1.1671.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.1.1671.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```
This difference in Appx Package name would also render the chocoUninstall.ps1 script (https://github.com/mkevenaar/chocolatey-packages/blob/master/automatic/microsoft-windows-terminal/tools/chocolateyUninstall.ps1) useless since it would not actually remove the preview version from Windows.

**Comment by ptanmay143** [comment]
The link (https://api.github.com/repos/microsoft/terminal/releases) provides a JSON output of all the releases (stable and pre-release both). The boolean key `prerelease` determines whether a release is a prelease or stable. To get the direct download link to the `.msixbundle` file of a specific release, one needs to traverse into the `assets` key array and look for the `browser_download_url` key.
Just for reference, I'm copying here only the above keys for the two releases in question (1.0.1401.0 and 1.1.1671.0).
```
[
    {
        [...]
        "tag_name": "v1.1.1671.0",
        [...]
        "prerelease": true,
        [...]
        "assets": [
            {
                [...]
                "browser_download_url": "https://github.com/microsoft/terminal/releases/download/v1.1.1671.0/Microsoft.WindowsTerminal_1.1.1671.0_8wekyb3d8bbwe.msixbundle"
            }
        ],
        [...]
    },
    {
        [...]
        "tag_name": "v1.0.1401.0",
        [...]
        "prerelease": false,
        [...]
        "assets": [
            {
                [...]
                "browser_download_url": "https://github.com/microsoft/terminal/releases/download/v1.0.1401.0/Microsoft.WindowsTerminalPreview_1.0.1402.0_8wekyb3d8bbwe.msixbundle"
            }
        ],
        [...]
    },
[...]
]

**Comment by mkevenaar** [comment]
Thank you for creating this issue. I will have a look at it soon.

**Comment by mkevenaar** [comment]
@ptanmay143 I ended up changing the work into a Stream to have a pre-release and a stable stream automatically updating in Chocolatey. They released a pre-release and a stable release at the same time.

You can see my changes in this commit: https://github.com/mkevenaar/chocolatey-packages/commit/8b14c50ef3f06b2a17b68df22af221cccb68fcea

**Comment by ptanmay143** [comment]
I tried installing Windows terminal on another system using `choco install -y microsoft-windows-terminal` but this still installed the preview version. How do I specifically install the stable version?

**Comment by mkevenaar** [comment]
@ptanmay143 They have split the software into two separate parts. Could you run the following in an elevated powershell?

```
choco uninstall microsoft-windows-terminal -n -y
Get-AppxPackage -Name Microsoft.WindowsTerminalPreview | Remove-AppxPackage
Get-AppxPackage -Name Microsoft.WindowsTerminal| Remove-AppxPackage
choco install microsoft-windows-terminal -n -y
```
This will uninstall the package, the two separate packages for Microsoft Windows Terminal and then it should install the latest version of Terminal without a pre-release.

Could you confirm that this is working for you so I can close this case again?

**Comment by ptanmay143** [comment]
The output of `choco uninstall microsoft-windows-terminal -n -y`:
```ps
Chocolatey v0.10.15
Uninstalling the following packages:
microsoft-windows-terminal

microsoft-windows-terminal v1.1.1671.0
 Skipping auto uninstaller - No registry snapshot.
 microsoft-windows-terminal has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
The outputs of `Get-AppxPackage -Name Microsoft.WindowsTerminalPreview | Remove-AppxPackage` and `Get-AppxPackage -Name Microsoft.WindowsTerminal | Remove-AppxPackage` are both blank.
The output of `choco install microsoft-windows-terminal -n -y`:
```ps
Chocolatey v0.10.15
Installing the following packages:
microsoft-windows-terminal
By installing you accept licenses for the packages.

Progress: Downloading microsoft-windows-terminal 1.1.1671.0... 0%
[...]
Progress: Downloading microsoft-windows-terminal 1.1.1671.0... 99%
Progress: Downloading microsoft-windows-terminal 1.1.1671.0... 100%

microsoft-windows-terminal v1.1.1671.0 [Approved]
microsoft-windows-terminal package files install completed. Performing other installation steps.
 The install of microsoft-windows-terminal was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
So, this still installs the `v1.1.1671.0` which is a pre-release version and another issue is that now there is no start menu entry for Windows Terminal or Preview either. Doing a `Get-AppxPackage -Name Microsoft.WindowsTerminal` and `Get-AppxPackage -Name Microsoft.WindowsTerminalPreview` now returns nothing.

**Comment by mkevenaar** [comment]
@ptanmay143 I have pulled that version just now. Can you run the commands again?

This should result in the installation of v1.0.1811.0 which should be the latest available release as of now.

If you want the latest pre-release you'll need to specifically add `--pre` to the command as shown here: 

https://chocolatey.org/packages/microsoft-windows-terminal/1.1.1812.0-beta

**Comment by ptanmay143** [comment]
`choco install microsoft-windows-terminal` still installs `v1.1.1671`.

**Comment by MortenBoysen** [comment]
I also followed these steps:

```
choco uninstall microsoft-windows-terminal -n -y
Get-AppxPackage -Name Microsoft.WindowsTerminalPreview | Remove-AppxPackage
Get-AppxPackage -Name Microsoft.WindowsTerminal| Remove-AppxPackage
choco install microsoft-windows-terminal -n -y
```

And it removed both packages. The last step installed the correct version, but I am also lacking a start menu entry. Hence I cannot start the terminal since I do not know where the binary is.

**Comment by ptanmay143** [comment]
> I also followed these steps:
> 
> ```
> choco uninstall microsoft-windows-terminal -n -y
> Get-AppxPackage -Name Microsoft.WindowsTerminalPreview | Remove-AppxPackage
> Get-AppxPackage -Name Microsoft.WindowsTerminal| Remove-AppxPackage
> choco install microsoft-windows-terminal -n -y
> ```
> 
> And it removed both packages. The last step installed the correct version, but I am also lacking a start menu entry. Hence I cannot start the terminal since I do not know where the binary is.

In the last command, you specified the `-n` option which skips running the chocoInstall.ps1 script. You could do a `choco install microsoft-windows-terminal --force`. I'll have to check tomorrow if it installs the correct version in my school laptop.

**Comment by MortenBoysen** [comment]
> > And it removed both packages. The last step installed the correct version, but I am also lacking a start menu entry. Hence I cannot start the terminal since I do not know where the binary is.
> 
> In the last command, you specified the `-n` option which skips running the chocoInstall.ps1 script. You could do a `choco install microsoft-windows-terminal --force`. I'll have to check tomorrow if it installs the correct version in my school laptop.

Cheers! That fixed the issue and everything seems to work as expected now. No preview installed and the correct version of the Windows Terminal is installed (1.0.1811.0)

**Comment by ptanmay143** [comment]
I can confirm that this does install the correct version on my school computer as well as my personal computer. I'm closing this issue now. Thanks.
