### ISSUE TITLE
(powertoys) out of date for a few days

### ISSUE THREAD

**Issue by SeanKilleen** [mkevenaar/chocolatey-packages#60]
PowerToys `v0.20.0` was released 7/31 and it announces the availability in my windows sidebar, but I hadn't seen any update via Chocolatey.

It hasn't been that long, so I assume an update is likely coming, but since these are automatic, I figured I'd add an issue just in case.

**Comment by mkevenaar** [comment]
Hi @SeanKilleen 

Thanks for creating this issue. I am aware of the new PowerToys release, however I am currently unable to update.

For more info see:
https://github.com/microsoft/PowerToys/issues/5381
https://chocolatey.org/packages/powertoys#comment-5016107595

**Comment by SeanKilleen** [comment]
Thanks for this information! I hope they're able to resolve it and I'll up-vote.

**Comment by mkevenaar** [comment]
@SeanKilleen A MSI installer has been provided by the PowerToys team. A new version of the package should be submitted soon.

**Comment by ArgonAlex** [comment]
Any news on a new version?
