### ISSUE TITLE
(chocolatey-isomount.extension) iso doesnt unmount if setup fails

### ISSUE THREAD

**Issue by Mahagon** [mkevenaar/chocolatey-packages#61]
## Expected Behavior
if the install doesn't exit with an success exitcode the iso should be unmounted

## Current Behavior
if the install doesn't exit with an success exitcode the iso stays mounted and will add another mounted drive on every run

## Possible Solution
try catch finally? -> finally does the dismount
https://github.com/mkevenaar/chocolatey-packages/blob/master/extensions/chocolatey-isomount.extension/extensions/Install-ChocolateyIsoInstallPackage.ps1#L161-L171

## Context
We are using a german language pack. and we try installing mssql with the parameter /ENU on it with puppet. if the english language pack is not installed the mssql setup will fail.

we worked around it

## Your Environment
* Package Version used: 1.0
* Operating System and version:  German Windows Server 2019 Standard
* Chocolatey version: 0.10.15

**Comment by mkevenaar** [comment]
@Mahagon thank you for creating this issue. I'll try to have a look at this soon.
Feel free to submit a PR if you want

**Comment by mkevenaar** [comment]
This has been fixed here: https://github.com/mkevenaar/chocolatey-packages/commit/7c0767de27af4e0fbd7b94a9cd0cbd7e76747393

A new version of the package will be pushed out soon.

**Comment by mkevenaar** [comment]
The package is in the queue, ready to be moderated:

https://chocolatey.org/packages/chocolatey-isomount.extension/1.0.1

You can use this version by specifying a version number: choco install chocolatey-isomount.extension --version=1.0.1
