### ISSUE TITLE
(Slack) Non-terminating error on upgrade if slack.exe is not running

### ISSUE THREAD

**Issue by wolffberg** [mkevenaar/chocolatey-packages#65]
## Expected Behavior
Installer should run without errors even if slack.exe is not running.

## Current Behavior
Non-terminating error is thrown when running `choco upgrade slack -y`

```
C:\> choco upgrade slack -y
Chocolatey v0.10.15
Upgrading the following packages:
slack
By upgrading you accept licenses for the packages.

You have slack v4.8.0 installed. Version 4.9.0 is available based on your source(s).
Cannot find a process with the name "slack". Verify the process name and call the cmdlet again.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
```

## Possible Solution
Set `ErrorAction` to `SilentlyContinue` in **chocolateyBeforeModify.ps1**
```powershell
Get-Process "slack" -ErrorAction SilentlyContinue | Stop-Process -Force
```

## Steps to Reproduce (for bugs)
1. `choco install slack --version 4.8.0 --allow-downgrade -y`
2. `choco upgrade slack -y`

## Context
When upgrading Slack a error message is printed to console indicating an error that does not affect the upgrade process.

## Your Environment

* Package Version used: 4.8.0 & 4.9.0
* Operating System and version: Windows 10 Version 2004 Build 19041.450
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by mkevenaar** [comment]
@wolffberg thanks for submitting this issue, I think it's a good addition for the package.

Are you willing to submit a PR for this?

**Comment by wolffberg** [comment]
PR created https://github.com/mkevenaar/chocolatey-packages/pull/66
