### ISSUE TITLE
(winrar) Broken because of repackaging due to certificate revocation

### ISSUE THREAD

**Issue by DigNative** [mkevenaar/chocolatey-packages#68]
## Expected Behavior
Installation of WinRAR via chocolatey should work without any issue.

## Current Behavior
The WinRAR installer cannot be downloaded because the checksum of the downloaded file is different to the expected one:
```
winrar v5.91 [Approved]
winrar package files install completed. Performing other installation steps.
Downloading winrar 64 bit
  from 'https://www.rarlab.com/rar/winrar-x64-591.exe'

Download of winrar-x64-591.exe (3.09 MB) completed.
Error - hashes do not match. Actual value was '892F7FDFDAF9FCEC6C035C8C65B280E18B7797620F4375699A2D4D41F60F794C'.
ERROR: Checksum for 'C:\Users\[REDACTED]\AppData\Local\Temp\chocolatey\winrar\5.91\winrar-x64-591.exe' did not meet '1c30d74f20ea721d63061d2a06ac00a9270fc7823004ff4f572d354990d4c1ae' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
 See log for details.
```

## Possible Solution
Update the hashes for all downloads in `tools\downloadInfo.csv`.

## Steps to Reproduce (for bugs)
Try to install the current version of the WinRAR package with Chocolatey.

## Context
The certificate used for the original WinRAR v5.91 packages was revoked. All downloads for this version have been repackaged using a different certificate, which causes the hashes of all downloads to be changed. I guess the automatic update mechanism cannot detect this as the version number of WinRAR itself did not change.

**Comment by mkevenaar** [comment]
Hi @DigNative 

thank you for checking this!

I have kicked of a new build and a new package should be available soon.

**Comment by mkevenaar** [comment]
This is the commit with the changed checksums: https://github.com/mkevenaar/chocolatey-packages/commit/3cb32d67aa5e857859e4cfaf29fba10c185ab94a

New package: https://chocolatey.org/packages/winrar/5.91.0.20200917

**Comment by DigNative** [comment]
Thank you very much for your very fast reaction and the fix!
