### ISSUE TITLE
(mysql) Issue with x86 PC

### ISSUE THREAD

**Issue by naveen521kk** [mkevenaar/chocolatey-packages#69]
## Expected Behavior
I installed MySql and it worked on my main PC. But when I tried the same for my Laptop which is 32 bit Windows 10, it installed but the software didn't work.

## Current Behavior
It gave me this error on my Laptop.
```cmd
C:\Users\Dell>"C:\tools\mysql\current\bin\mysqld" --console
This version of C:\tools\mysql\current\bin\mysqld.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
## Possible Solution
It looks like the upstream doesn't have zip files for x86 PC so the package should check for `x86` using `Get-OSArchitectureWidth` and stop the installation informing the user.

## Steps to Reproduce (for bugs)

1. Use a 32 bit PC.
2.  Type `choco install mysql`
3.  Type `"C:\tools\mysql\current\bin\mysqld" --console`. This should run MySQL but doesn't run and shows not supported as above.

## Context
I need to install MySql in my Laptop and for my school work where they teach me how to use this software.

## Your Environment
* Package Version used: 8.0.21
* Operating System and version:  Microsoft Windows 10 Pro 10.0.18363 N/A Build 18363
* Chocolatey version: v0.10.15
* Install/uninstall gist:  https://gist.github.com/naveen521kk/ea77ee50cb64c1820669169ecb17b73d

**Comment by mkevenaar** [comment]
Hi @naveen521kk thanks for noticing!

This has been fixed and will get pushed on a next release of MySQL

**Comment by naveen521kk** [comment]
Also, a small suggestion there had been many red coloured outputs while installing possibly because of  `Start-ChocolateyProcessAsAdmin`. I suggest using something else to fix it because sometimes it looks pretty scary.

I suggest directly calling is batch scripts using `& "<batch script name>" -params` could possibly fix it and also is there an issue for that on chocolatey?
@mkevenaar

**Comment by mkevenaar** [comment]
Hi @naveen521kk 

calling `Start-ChocolateyProcessAsAdmin` is the best way to go when calling an executable or a batch script inside Chocolatey packages. 

I am not sure if there is an issue for that, best to check over at the https://github.com/chocolatey/choco repo

**Comment by naveen521kk** [comment]
Here https://github.com/chocolatey/choco/issues/1016
> calling Start-ChocolateyProcessAsAdmin is the best way to go when calling an executable or a batch script inside Chocolatey packages.

Why is it so? Also, it is nearly for many users whom I recommend to install MySQL using chocolatey were literally frightened on seeing some weird red coloured outputs. I don't think it is problem with this package though.

**Comment by mkevenaar** [comment]
@naveen521kk it aserts that you have admin privileges. Chocolatey could be used in a non-admin environment. 

for more info about the helper, have a look at the [documentation](https://chocolatey.org/docs/helpers-start-chocolatey-process-as-admin)
