### ISSUE TITLE
Virus found in the source url https://chocolatey.org/packages/iobit-malware-fighter/8.2.0.685#files - URGENT

### ISSUE THREAD

**Issue by SUPRVISOR** [mkevenaar/chocolatey-packages#72]
Hello

I inform you that the source for the software iobit-malware-fighter / 8.2.0.685 is infected Windows categorizes it as "Serious" Trojan

Choco also informs that the checksum is not good.

Your source:
http://update.iobit.com/dl/IObit-Malware-Fighter-Setup.exe

My official source tested is no problem:
http://cdn.iobit.com/dl/IObit-Malware-Fighter-Setup.exe

I let you change the source in order to avoid future problems and also change the checksum which does not work.

Best Regards.
SUPERVISOR.

**Comment by mkevenaar** [comment]
Hi @SUPRVISOR 

I do not own / maintain the IOBit Software. Best to reach out to them regarding (possible) viruses in their software.

Regarding the checksum, I could trigger a new build.

**Comment by SUPRVISOR** [comment]
hi
I look who takes care of it thank you and I tell them
Best Regards.
SUPERVISOR

**Comment by mkevenaar** [comment]
The source has been changed and will be used on the next version of the package.
