### ISSUE TITLE
(powertoys) package is not automatically updating from 0.21.1 to 0.23.0

### ISSUE THREAD

**Issue by treischl** [mkevenaar/chocolatey-packages#74]
## Expected Behavior

The package should automatically update when a new version is available on [Github](https://github.com/microsoft/PowerToys/releases/latest)

## Current Behavior

Currently the package is stuck at 0.21.0 while the latest release is 0.23.0.

## Possible Solution

It appears that the [update.ps1](https://github.com/mkevenaar/chocolatey-packages/blob/78d69e93c3952901a478e404bf240f9d6d675a2b/automatic/powertoys/update.ps1#L10) looks for a linked release asset with an _.msi_ file extension. While previous releases have included separate _.msi_ and _.exe_ assets, the current release only has a _.exe_ asset, and the following line from the release notes indicates this may be the norm going forward:

> * The EXE installer should be at parity now with the MSI. Please go to the wiki for [installer args](https://github.com/microsoft/PowerToys/wiki/Installer-arguments-for-exe)

A possible solution might be to search for the _.exe_ asset instead of the _.msi_ asset:

```diff
@@  chocolatey-packages/automatic/powertoys/update.ps1
-    $re  = "PowerToysSetup(.+)?.msi"
+    $re  = "PowerToysSetup(.+)?.exe"
```

If the above change is appropriate, I can submit the [pull request](https://github.com/mkevenaar/chocolatey-packages/compare/master...treischl:fix-powertoys-auto-update) to help expedite the process.

## Steps to Reproduce (for bugs)

1. Install powertoys via chocolatey: `choco install powertoys -y`.
2. Within the next 24 hours, powertoys will provide a notification that version 0.23.0 is available.
3. Verify package with version 0.23.0 is not available: `choco list powertoys -e`.

## Context

I prefer to install and upgrade software using chocolatey when possible. This has prevented me from updating the powertoys package to the latest version.

## Your Environment

* Package Version used: 0.21.1
* Operating System and version: Windows 10 Pro 2004
* Chocolatey version: 0.10.15

**Comment by mkevenaar** [comment]
@treischl thank you for this issue. I am going to pick this up. Unfortunately the package will now require some extra dependencies and additional parameters. 

https://github.com/microsoft/PowerToys/wiki/Installer-arguments-for-exe
