### ISSUE TITLE
(icloud) fails with error 1603

### ISSUE THREAD

**Issue by artmg** [mkevenaar/chocolatey-packages#75]
`choco install -y icloud` fails with error 1603

## Expected Behavior
* Install completes without errors
* Add Remove Programmes (ARP) includes the entries `iCloud 7.21.0.23` as well as App Support and Bonjour mentioned below
* Start Menu includes an `iCloud` folder with 11 icons such as `Calendar,` `Contacts` etc
    * _I am unclear whether there should be a Start Menu `Apple Software Update` entry and an ARP item `Apple Software Update 2.6.3.1`_

## Current Behavior
* Error during install, even though the wrapper accepts the 1603 error
    * See below for the errors output by choco onto the console
* The icloud software is not installed by the choco package, it appears that the MSI undoes all the changes
* Non of the signs of the app are present in Start Menu, and ARP only contains `Apple Application Support (64-bit) 8.7` and `Bonjour 3.0.0.10`

## Possible Solution
* Workaround: manually executing the the same install package downloaded from the url mentioned in https://github.com/mkevenaar/chocolatey-packages/blob/master/automatic/icloud/tools/chocolateyinstall.ps1 
* Maybe some new options need to be specified in the wrapping

## Steps to Reproduce (for bugs)
1. Fresh install of Windows 10 out of the box
2. finish all updates and restarts required
3. Install chocolatey
4. Install the choco apps: `choco-upgrade-all-at-startup  zoom  skype  skype-disable-updates-winconfig` - I don't know if these were necessary but I'm telling you what I did
5. `choco install -y icloud --force --install-arguments="'/l*v c:\iCloud_msi_install.log'"`
6. See resulting **chocolatey log** at https://pastefs.com/pid/243674 and **msi log** at https://pastefs.com/pid/243665

## Context
* I have to use a manual install, and rely on the Apple updater

## Your Environment
* Package Version used: Apple iCloud 7.21.0.23
* Operating System and version: Windows 10 Home 2004 19041.572
* Chocolatey version: 0.10.15
* Install/uninstall gist: choco install -y icloud --force --install-arguments="'/l*v c:\iCloud_msi_install.log'"

## choco error output

```
choco install -y icloud --force --install-arguments="'/l*v c:\iCloud_msi_install.log'"
Chocolatey v0.10.15
Installing the following packages:
icloud
By installing you accept licenses for the packages.
Progress: Downloading iCloud 7.21.0.23... 100%
iCloud v7.21.0.23 (forced) [Approved]
icloud package files install completed. Performing other installation steps.
Downloading iCloud
  from 'http://updates-http.cdn-apple.com/2020/windows/001-39935-20200911-1A70AA56-F448-11EA-8CC0-99D41950005E/iCloudSetup.exe'
Progress: 100% - Completed download of C:\Users\Me\AppData\Local\Temp\chocolatey\iCloud\7.21.0.23\iCloudSetup.exe (153.68 MB).
Download of iCloudSetup.exe (153.68 MB) completed.
Hashes match.
Extracting C:\Users\Me\AppData\Local\Temp\chocolatey\iCloud\7.21.0.23\iCloudSetup.exe to C:\Users\Me\AppData\Local\Temp\chocolatey\iCloud\7.21.0.23...
C:\Users\Me\AppData\Local\Temp\chocolatey\iCloud\7.21.0.23
Installing 64-bit AppleApplicationSupport64.msi...
AppleApplicationSupport64.msi has been installed.
Installing 64-bit Bonjour64.msi...
Bonjour64.msi has been installed.
Installing 64-bit iCloud64.msi...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\iCloud_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
WARNING: Exit code '1603' was considered valid by script, but not as a Chocolatey success code. Returning '0'.
iCloud64.msi has been installed.
  icloud may be able to be automatically uninstalled.
 The install of icloud was successful.
  Software installed to 'C:\Program Files (x86)\Bonjour\'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

More extensive logs available: 
* **chocolatey log** at https://pastefs.com/pid/243674
* **msi log** at https://pastefs.com/pid/243665

**Comment by mkevenaar** [comment]
@artmg the error code 1603 is basically the mother of all error codes. Looking at the log I can't find an obvious reason why iCloud failed.

Would you be able to restart your computer and try again?

**Comment by artmg** [comment]
After a restart there was no change in behaviour. I did a manual install via the exe, which worked, and I then uninstalled it manually. After a further restart I then reattempted choco install and the issue still arose. It's been a while since I scoured MSI Action logs, but is there not something in the msi log attached at https://pastefs.com/pid/243665 that gives at least some clue. Is there not a line in there that tells us when the MSI started to not like what was happening?

**Comment by TFenby** [comment]
This is still a problem in '22 (almost '23), and probably the same problem considering that this was submitted in October of 2020 and the iCloud64.msi file that's downloaded has a modification date of 9/8/2020. 

Going into the Choco temp folder and running that MSI from Explorer gives the following:
```
There is a problem with this Wlndows Installer package.
A program run as part of the setup did not finish as expected. Contact your personnel or package vendor.
```

I chased it for a little bit and got this in the MSI install logs:
```
MSI (s) (18:AC) [14:07:14:949]: Executing op: ActionStart(Name=RuniCloudUpgrade,,)
MSI (s) (18:AC) [14:07:14:949]: Executing op: CustomActionSchedule(Action=RuniCloudUpgrade,ActionType=1570,Source=C:\Program Files (x86)\Common Files\Apple\Internet Services\,Target=C:\Program Files (x86)\Common Files\Apple\Internet Services\iCloud.exe /upgrade,)
MSI (s) (18:AC) [14:07:14:949]: Executing op: End(Checksum=0,ProgressTotalHDWord=0,ProgressTotalLDWord=0)
MSI (s) (18:AC) [14:07:14:951]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (18:AC) [14:07:14:951]: User policy value 'DisableRollback' is 0
MSI (s) (18:AC) [14:07:14:951]: Machine policy value 'DisableRollback' is 0
MSI (s) (18:AC) [14:07:14:952]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (18:AC) [14:07:14:972]: Note: 1: 1722 2: RuniCloudUpgrade 3: C:\Program Files (x86)\Common Files\Apple\Internet Services\ 4: C:\Program Files (x86)\Common Files\Apple\Internet Services\iCloud.exe /upgrade 
CustomAction RuniCloudUpgrade returned actual error code 2147483647 (note this may not be 100% accurate if translation happened inside sandbox)
```

The referenced PFx86 folder didn't exist, and I also couldn't find iCloud.exe anywhere on my machine. However, running iCloudSetup.exe in the same folder did work and I do now have iCloud installed. So my guess would be that something with the ordering of Chocolatey's install instructions for iCloud differs from Apple's .exe installer.
