### ISSUE TITLE
JetBrains Rider gets installed to Program Files (x86) which breaks its batch script

### ISSUE THREAD

**Issue by ForNeVeR** [mkevenaar/chocolatey-packages#76]
## Expected Behavior
`choso install jetbrains-rider` should install Rider to `C:\Program Files\JetBrains\JetBrains Rider 2020.2.4\`

## Current Behavior
`choso install jetbrains-rider` installs Rider to `C:\Program Files (x86)\JetBrains\JetBrains Rider 2020.2.4\`, which leads to `rider.bat` being broken (see [IDEA-254793](https://youtrack.jetbrains.com/issue/IDEA-254793)).

## Possible Solution
Not using `rider.bat` after Rider installation (which is what most users do).

## Steps to Reproduce (for bugs)
1. `choso install jetbrains-rider`
2. `"C:\Program Files (x86)\JetBrains\JetBrains Rider 2020.2.4\bin\rider.bat"`
3. You'll see the console output `\JetBrains\JetBrains was unexpected at this time.`
   Rider won't start.

## Context
Honestly, I don't know under which circumstances users could want to use the Batch file instead of `rider64.exe`, but practice shows they sometimes are doing that.

## Your Environment
* Package Version used: `2020.2.4`, latest available at the moment
* Operating System and version: Windows 10 Version 2004
* Chocolatey version: `0.10.15`

**Comment by mkevenaar** [comment]
Hi @ForNeVeR,

Thank you for submitting this issue.

Unfortunately, I am not specifying any installation folder for this software. I don't know why the installer installs in the `Program Files (x86)` folder. I am only telling it to install silently

First of all, I think the install folder is a bug in the JetBrains installers. I have seen this happening with all of their software and silent installations.

Other than that, the batch file is installed by the software. Obviously I am not allowed to make any changes to the installed data without the user's permission.

I don't think I can do anything to help you here :(

Cheers,

Maurice

**Comment by ForNeVeR** [comment]
> First of all, I think the install folder is a bug in the JetBrains installers. I have seen this happening with all of their software and silent installations.

Yes, this is possible. I'll investigate and let you know of results.

Thanks for taking a look!

**Comment by ForNeVeR** [comment]
Also, something's wrong with the stale bot removing a label you've just added, @mkevenaar :)
