### ISSUE TITLE
(Evernote) automatic updates not running?

### ISSUE THREAD

**Issue by SeanKilleen** [mkevenaar/chocolatey-packages#78]
Hi! Thank you for making packages available for us folks. :) 

It looks like we're missing some of the latest releases, e.g. https://cdn1.evernote.com/boron/win/builds/Evernote-10.3.7-2018-setup.exe.

I looked at the `update.ps1` script and as far as I can tell all the matching etc. is correct. Is it possible that the automatic packages aren't running?

I'm going to submit a PR that updates the manual listing with the URL and Sha256 checksum in case that makes it easier to get a release out; feel free to ignore both of these if I'm missing the issue.

**Comment by mkevenaar** [comment]
Hi @SeanKilleen 
thanks for letting me know!
Unfortunately the PR you submitted isn't going to work. 
I have fixed my update.ps1 file, it now detects the new V10 version. A new version has been pushed to Chocolatey and will be available soon.

**Comment by SeanKilleen** [comment]
Ahh, interesting -- I'd looked at what might have been wrong but couldn't find it. I'll learn from your update; much appreciated! 👍 I'll close my PR.
