### ISSUE TITLE
iobit uninstaller package is very out of date

### ISSUE THREAD

**Issue by WHiZSTA** [mkevenaar/chocolatey-packages#81]
the iobit uninstaller package is very out of date
your version states 9.6.0.3
latest free version on iobit's site is 10.1.21 updated oct 20th
https://download.cnet.com/IObit-Uninstaller/3000-2096_4-75161625.html?part=dl-&subj=dl&tag=button

**Comment by mkevenaar** [comment]
@WHiZSTA Thank you for submitting this issue, I have committed a fix. A new package version should be available soon.
