### ISSUE TITLE
(viber) Register application

### ISSUE THREAD

**Issue by majkinetor** [mkevenaar/chocolatey-packages#85]
It would be great to be able to start viber using Win+R which is currently not possible.

For that to work, you need to use this:

```ps1
$installLocation = Get-AppInstallLocation "$packageName*"
if (!$installLocation)  { Write-Warning "Can't find $packageName install location"; return }
Write-Host "$packageName installed to '$installLocation'"

Register-Application "$installLocation\$packageName.exe"
Write-Host "$packageName registered as $packageName"
```

or add it to the PATH which is IMO not necessary.

If you want to accept it I can test it out and make a PR ?

**Comment by mkevenaar** [comment]
@majkinetor Sure, feel free to submit a PR ;)
